### ISSUE TITLE
Updating `tests/failing-symbolic.haskell`

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/evm-semantics#1036]
- Make sure you have `timeout` and GNU `time` installed (not bash builtin `time`).
- Put this script somewhere on `PATH` called `profile`:

  ```
  #!/usr/bin/env bash

  set -euo pipefail

  test_log="$1" ; shift
  mkdir -p $(dirname "$test_log")
  exit_status='0'
  `which time` --quiet --format '%x %es %Us %Ss %MKB %C' --output "$test_log" --append \
      "$@" &>/dev/null \
      || exit_status="$?"
  exit "$exit_status"
  ```

- Remove/clear the file `tests/failing-symbolic.haskell`
- Make sure you have `timeout` command installed.
- `make test-prove -j8 -k KEVM='profile log timeout 3000 kevm' TEST_SYMBOLIC_BACKEND=haskell`
- Use the output in `log` to update the file `tests/failing-symbolic.haskell`. Exit-code 124 means it timed out (3000s). Exit-code 0 is success. Any other exit-code is the prover failing.
- For example, to get all non-success tests:
  `grep '^[^0]' log | grep 'tests.*\.k' -o | sort > tests/failing-symbolic.haskell`

**Comment by Riib11** [comment]
Output of re-running tests here: https://github.com/kframework/evm-semantics/blob/try-tests/try-tests.out

**Comment by JKTKops** [comment]
I'm taking this one this time.

**Comment by ehildenb** [comment]
Start debugging (look at `make --dry-run test-prove` to get all the correct options for `kevm`):

- Start 5 parallel runs of `kevm prove --backend haskell PROOF__YOU_CARE_ABOUT VERIFICATION ... --depth 10 &> output.10` with `--depth` set to 10, 100, 250, 500, 1000.
- At the same time, you can do a run of `kevm prove ... --debugger --debug-script kscript`.

`kscript`:

```
alias konfig = config | kast -i kore -o pretty -d .build/usr/lib/kevm/haskell /dev/stdin
```

It's going to immediately complain about symbols `#gas` and `#buf` not be unparseable.

Use this branch (after merging to master) if you want to use the `kore-repl`: https://github.com/kframework/evm-semantics/pull/1034/files
