### ISSUE TITLE
Build K, KEVM, and Both Backends

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/evm-semantics#1074]
From a fresh clone of KEVM, we should be able to build it from source. This means these commands work:

```
git clone 'https://github.com/kframework/evm-semantics'
cd evm-semantics
git submodule update --init --recursive
make deps RELEASE=true -j8
make build RELEASE=true -j8
```

Following the build instructions above ^^^, you should make sure that you can also run some of the tests:

```
make test-conformance -j8 # llvm backend
make test-prove -j8 TEST_SYMBOLIC_BACKEND=haskell # haskell backend
make test-prove -j8 TEST_SYMBOLIC_BACKEND=java # java backend
```

### Raoul

- [x] Build dependencies and semantics (`make deps` and `make build`).
- [x] Run the concrete tests (`make test-conformance`)
- [x] Run the symbolic tests (`make test-prove`).

**Comment by ehildenb** [comment]
If you're on a Mac https://github.com/kframework/evm-semantics/issues/1022

On Windows, use WSL2.

**Comment by ehildenb** [comment]
We do have a binary cache for the Nix packages, which it would be good to try, to make sure we have a larger bus factor than 1.

@andreiburdusa can you point us to the instructions for setting up the binary cache?

**Comment by ehildenb** [comment]
We'll leave this one open, for when @RaoulSchaffranek gets his new machine. Then we can try the Nix version of the install again.

**Comment by andreiburdusa** [comment]
> We do have a binary cache for the Nix packages, which it would be good to try, to make sure we have a larger bus factor than 1.
> 
> @andreiburdusa can you point us to the instructions for setting up the binary cache?

For kore, we have [these instructions](https://kore.cachix.org/) linked from [Developing with Nix](https://github.com/kframework/kore#developing-with-nix). Is this what you are looking for?

**Comment by ehildenb** [comment]
Will that same binary cache also work for the K repo Nix build, or just Kore @andreiburdusa ?

**Comment by andreiburdusa** [comment]
> Will that same binary cache also work for the K repo Nix build, or just Kore @andreiburdusa ?

```
andrei@q:~/k$ nix-build -A k
copying path '/nix/store/k7mnwba0x8bvdh7rplx93wwf4559sg2l-kore-stack-to-nix-pkgs' from 'https://kore.cachix.org'...
building '/nix/store/7r9djpy19zkifqzp286l0m5bj65ysl5n-git-ls-files.drv'...
building '/nix/store/k2xyx7n8fqr0dpql221cv32qz2w0k4f2-git-ls-files.drv'...
...
```
The first output line makes me think it works for K as well, but I'm not entirely sure

**Comment by RaoulSchaffranek** [comment]
Thanks, everybody. The binary cache solved my problem, namely that `nix-build` built everything (including GHC and Cabal) from source. I can confirm, that the binary cache also works for the k frontend.

I think it would be a good idea to mention the binary cache in the [Building with Nix](https://github.com/kframework/k/blob/master/README.md#building-with-nix) section of the K-frontend Readme file. Otherwise building with Nix can take hours. I will prepare a PR.
