### ISSUE TITLE
Try out provex with debugger

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/evm-semantics#1123]
To get commands to run:

```
make tests/specs/mcd/cat-file-addr-pass-rough-spec.k.provex TEST_SYMBOLIC_BACKEND=haskell
```

Something like this to kompile:

```
make tests/specs/mcd/verification/haskell/verification-kompiled/timestamp
```

To run debugger, add `--debugger --debug-script ....`

```
kevm prove tests/specs/mcd/cat-file-addr-pass-rough-spec.k --verif-module VERIFICATION --backend-dir ... --provex
--debugger --debug-script ...
```

Try using `kore-print` instead of `kast`.

Post here how to do this whole thing using new toolchain, and any problems that show up.

**Comment by calin1304** [comment]
After trying out `provex` and `kore-print` I can say this is a nice improvement.
- I didn't have any issues with `NoSuchElementException` when trying to pretty print the configuration
- `kore-print` is so much faster than `kast`
- one thing to mention is that doing something like `make tests/specs/mcd/verification/haskell/verification-kompiled/timestamp` will compile the verification modules in `tests/specs/mcd/verification/haskell`, which I used when doing `kore-print -d tests/specs/mcd/verification/haskell -o pretty -`. Having a generic alias that uses `-d .build/usr/lib/kevm/haskell` won't work, we'll have to use a more specific path to the spec directory.
