### ISSUE TITLE
Execution of all test proofs in KEVM (Profiling)

### ISSUE THREAD

**Issue by ACassimiro** [runtimeverification/evm-semantics#1165]
To perform the execution of all test proofs available in the KEVM repository (a process referred to as 'profiling'), first you should follow the instructions available in the [README.md file of this repository](https://github.com/kframework/evm-semantics#installingbuilding) for the installation of the KEVM project in your machine. 

Once you're done with the installation of KEVM, install [GNU-Time](https://www.gnu.org/software/time/). Please, test your installation of GNU-Time to avoid silent crashes when running the profiling.

With KEVM and GNU-time ready, create the following scripts in the root of your KEVM repository:

- Script name: `profile`

```
#!/usr/bin/env bash
        
set -euo pipefail

test_log="$1" ; shift
mkdir -p $(dirname "$test_log")
exit_status='0'
`which time` --quiet --format '%x %es %Us %Ss %MKB %C' --output "$test_log" --append \
    "$@" &>/dev/null \
    || exit_status="$?"
exit "$exit_status"
```

When running the profiling with haskell backend, to execute all proofs, including the ones that are currently failing in this backend, please erase all the contents of the file `evm-semantics/tests/failing-symbolic.haskell`.

Finally, to run the profiling with the haskell backend, run the following command in your KEVM root directory:

`make test-prove KEVM='./profile log timeout 3000 kevm' -j6 -k`

This command will run all proofs in the nested directories of `test/specs/`, running at most 6 proofs at a time and with a maximum execution time per proof of 3000 seconds. It is important to highlight that the profiling is a memory intensive and time consuming process. For machines with less than 64GB of RAM, it is recommended to run a lesser number of simultaneous jobs, which can be achieved by changing the value 6 in the parameter `-j6` to the desired amount of maximum simultaneous jobs to be executed during the profiling. Also, as to avoid losing the output the profiling, you can redirect the output of the command above to a file named `output.txt` by adding `&> output.txt` at the end of the command.

For more information about the inner workings of the profiling execution, please read [this project's Makefile](https://github.com/kframework/evm-semantics/blob/master/Makefile).

-----

Setting up `kore-repl`:

- Script name: `print`

```
kore-print --definition tests/specs/mcd/verification/haskell /dev/stdin
echo
```

- Script name: `kscript`

```
alias konfig = config | bash print
```

Run `kevm prove` with `--debug-script kscript` (or just run `kprove` with thi sargument).

**Comment by ehildenb** [comment]
If you want to test out KEVM against a specific version of the Haskell backend, you can use this script (in conjunction with the profiling instructions above):

```
#!/usr/bin/env bash

set -euo pipefail

haskell_backend_version="$1" ; shift

git fetch --all
pushd deps/k/haskell-backend/src/main/native/haskell-backend
git fetch --all
git checkout "${haskell_backend_version}"
popd

make deps RELEASE=true
make build-provex -j8 RELEASE=true
make test-prove TEST_SYMBOLIC_BACKEND=haskell KEVM='./profile log timeout 3000 kevm' -j6 -k
```

**Comment by JKTKops** [comment]
For testing against several specific versions of the Haskell backend in sequence (for comparison), it is useful to make sure the logs go to different places. One simple way to do this is to modify the script like so (relevant lines indicated)
```bash
#!/usr/bin/env bash

set -euo pipefail

haskell_backend_version="$1" ; shift
logfile="logs/$haskell_backend_version/profile/prove-haskell" # this line is new

git fetch --all
pushd deps/k/haskell-backend/src/main/native/haskell-backend
git fetch --all
git checkout "${haskell_backend_version}"
popd

make deps RELEASE=true # I added SKIP_LLVM=true here but you may not want that
make build-provex -j8 RELEASE=true # -j4 to hog less memory
# below line now has $logfile instead of log
make test-prove TEST_SYMBOLIC_BACKEND=haskell KEVM="./profile $logfile timeout 3000 kevm" -j6 -k
```

This is not quite compatible with Everett's python script if you use a version identifier like `origin/master` (because of the extra slash). I will modify the python script to be happier about this tomorrow and then update here.

**Comment by fiedlr** [comment]
If one wants to run the profiling on macOS and use the above scripts, it is necessary to install `coreutils` (i.e., with `brew` this would be `brew install coreutils`). This is because the scripts depend on the `timeout` binary, which isn't included on macOS by default (I checked macOS Monterey).

**Comment by jinxinglim** [comment]
For the very first comment of this issue describing how to profile KEVM test proofs, under the section on setting up `kore-repl`, the content of the `print` script should be: 

```
kore-print --definition tests/specs/mcd/verification/haskell /dev/stdin
echo
```

instead of `--directory`.

**Comment by ehildenb** [comment]
Outdated
