### ISSUE TITLE
Error in macOS

### ISSUE THREAD

**Issue by lisandrasilva** [runtimeverification/evm-semantics#1192]
Following the instructions to [build kevm](https://github.com/kframework/evm-semantics) I was getting errors when running `make build` on macOs BigSur (version 11.0.1).

```
bash --version:
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)
```
```
make --version
GNU Make 3.81
```

### Fixes

1. Add KEVM to path:
```
export PATH=$(pwd)/.build/usr/bin:$PATH
``` 
2. Add the following line at the beginning of `Makefile`:
```
SHELL = /bin/bash -o pipefail
```
3. In the `kevm` file (in the root of the repository) delete the character `&` in the end of lines 74 and 75:
```
 llvm)      kompile_opts+=( --md-selector 'k & ! nobytes & ! node' )                         ;;
 node)      kompile_opts+=( --md-selector 'k & ! nobytes & ! standalone' --no-llvm-kompile ) ;;
 ```

Finally, running the following command should work:
```
make build-haskell build-provex -j2
```

**Comment by yanliu18** [comment]
This solution worked for me on macOS Monterey (version 12.2.1).
Additionaly, I ran into the solc: command not find error.
This can be solved installing solidity compiler (version > 8.0).

```
brew update
brew upgrade
brew tap ethereum/ethereum
brew install solidity
```

Further details are referred to the[ installation instructions](https://docs.soliditylang.org/en/v0.8.12/installing-solidity.html#macos-packages).

**Comment by fiedlr** [comment]
Actually 2. can be also fixed with installing a new version of bash with Homebrew. The old version that is default on macOS doesn't support some of the features in `Makefile`, that is why it is complaining about the `&`. 

Both 1. and 2. have been addressed in the updated README, @ehildenb should I close this?
