### ISSUE TITLE
`warn_unused_result` on NixOS

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/evm-semantics#1243]
When compiling on NixOS, the installed version of libcxx breaks:
```
/home/sam/git/evm-semantics/node/vm/main.cpp:75:9: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
        fread((char *)&len, 4, 1, _if);
        ^~~~~ ~~~~~~~~~~~~~~~~~~~~~~~
```

@goodlyrottenapple Please supply a Nix shell that I can use to dig into this further, once https://github.com/runtimeverification/k/issues/2577 has been resolved. Feel free to unassign yourself once you've done so

**Comment by goodlyrottenapple** [comment]
Fixed by #1262
