### ISSUE TITLE
`package/test-package.sh` segfaults on M1 Macs

### ISSUE THREAD

**Issue by goodlyrottenapple** [runtimeverification/evm-semantics#1303]
Running  the `package/test-package.sh` script on the M1 causes a segfault, specifically at the following test:
```bash
kevm run tests/failing/static_callcodecallcodecall_110_OOGMAfter_2_d0g0v0.json --backend llvm \
    --mode NORMAL --schedule BERLIN --chainid 1

/nix/store/0n0jrh6m1q7161rkngkh327zlw6196si-k-5.3.113-ee884e8d0dbe3a46e1d046a93baf0ae6a3a393cb-maven/bin/../lib/kframework/k-util.sh: line 85: 91070 Segmentation fault: 11  "$@"
[Error] krun: Backend crashed during rewriting with exit code 139
```

**Comment by F-WRunTime** [comment]
@Baltoli @goodlyrottenapple  Was this investigated as part of a different project board? 
Or something that was blocked until we got builds running on the M1? 

We're at the point this can either be removed or pulled in to check out on the M1.

**Comment by Baltoli** [comment]
Looking into it now.
