### ISSUE TITLE
More specific pyk definition for KToken('FoundryCheat . Failed')

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/evm-semantics#1336]
https://github.com/runtimeverification/evm-semantics/blob/master/kevm-pyk/src/kevm_pyk/solc_to_k.py#L360

Here, we are building the term `KToken('FoundryCheat . Failed')`. But `Failed` is not th ecorrect field name, so K will treat this as a variable, not as the actual failed storage slot address.

We should instead be building it directly as an AST, so that we get an error if the corresponding symbols don't exist.

**Comment by ehildenb** [comment]
Actually, `FoundryCheat` is not defined either. So it's fully a variable as well.

**Comment by ehildenb** [comment]
There is also something going wrong because the `_` is removed from the `failed` variable, but it definitely shows up in `test.sol` at `tests/foundry/lib/forge-std/lib/ds-test/src/test.sol`

**Comment by ehildenb** [comment]
Ah, but we are using the function `failed()` instead to access it.

**Comment by ehildenb** [comment]
I think we need to actually just take the post-state, and invoke the `failed()` function on it, to find out if the overall test failed or not.

**Comment by ehildenb** [comment]
Also, it appears we should be checking the `HEVM_ADDRESS`, not the `FoundryCheat` address:

https://github.com/dapphub/ds-test/blob/master/src/test.sol#L47

**Comment by ehildenb** [comment]
This is th egenerated code:

```
    syntax LoopsTestField ::= "IS_TEST" [symbol(), klabel(field_LoopsTest_IS_TEST)]
    
    syntax LoopsTestField ::= "failed" [symbol(), klabel(field_LoopsTest_failed)]

    syntax LoopsTestField ::= "IS_SCRIPT" [symbol(), klabel(field_LoopsTest_IS_SCRIPT)]
    
    syntax LoopsTestField ::= "stdstore" [symbol(), klabel(field_LoopsTest_stdstore)]

    rule  ( #loc ( LoopsTest . IS_TEST ) => 0 )
    

    rule  ( #loc ( LoopsTest . failed ) => 0 )


    rule  ( #loc ( LoopsTest . IS_SCRIPT ) => 0 )


    rule  ( #loc ( LoopsTest . stdstore ) => 1 )
```

Note that it should be `LoopsTest . _failed`, why is it `failed`?

**Comment by ehildenb** [comment]
Looking at `tests/foundry/out/DealTest.t.sol/DealTest.json`, we indeed get that the underbar is missing:

```
      {
        "astId": 90,
        "contract": "test/DealTest.t.sol:DealTest",
        "label": "failed",
        "offset": 1,
        "slot": "0",
        "type": "t_bool"
      },
```

**Comment by anvacaru** [comment]
I've doublechecked remix with 
```Solidity
Assert.equal(address(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D),address(bytes20(uint160(uint256(keccak256('hevm cheat code'))))), "t");
```
to check that the address used in  
```
rule #address(FoundryCheat) => 645326474426547203313410069153905908525362434349  // 0x7109709ECfa91a80626fF3989D68f67F5b1DD12D
```
 [defined here](https://github.com/runtimeverification/evm-semantics/blame/anvacaru/deal-fix/foundry.md#L38) is indeed the correct address.

**Comment by ehildenb** [comment]
This `FoundryCheat . Failed` is defined in `foundry.md`: https://github.com/runtimeverification/evm-semantics/blob/master/foundry.md#foundry-success-predicate
