### ISSUE TITLE
Implement assume and expectRevert cheatcodes

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/evm-semantics#1345]
Add tests of `Vm.assume` and `Vm.expectRevert` (all three forms of it) in `test/SimpleTest.t.sol` in a new module.

Then implement these cheat codes.

We need to have 4 different types of tests:

- Tests marked as passing (eg. `test_example`), that are actually passing.
- Tests marked as passing (eg. `test_exampel`), that are actually failing.
- Tests marked as failing (eg. `testFail_example`) that are actually failing.
- Tests marked as failing (eg. `testFail_example`) that are actually passing.

**Comment by anvacaru** [comment]
Assume is already implemented. No concrete work on `expectRevert` yet.
