### ISSUE TITLE
macOS Monterey has problems with running claims

### ISSUE THREAD

**Issue by fiedlr** [runtimeverification/evm-semantics#1354]
Even though I successfully ran the profiling after installing `coreutils` (I posted to https://github.com/runtimeverification/evm-semantics/issues/1165), after switching to `tests-fix` branch the individual test `collectToken-spec` I wanted to fix failed to run:

```
ja@ja-mbp evm-semantics % timeout 3000 kevm prove tests/specs/bihu/collectToken-spec.k --backend haskell --definition tests/specs/bihu/verification/haskell
[Error] Outer Parser: Module LEMMAS previously declared at
Source(/Users/ja/dev/evm-semantics/tests/specs/lemmas.k) and
Location(5,1,107,10)
	Source(/Users/ja/dev/evm-semantics/tests/specs/lemmas.k)
	Location(5,1,141,10)
	    .	v~~~~~~~~~~~~
	5 |	module LEMMAS
	    |		...
	141 |	endmodule
	    .	~~~~~~~~^
[Error] Outer Parser: Module LEMMAS-HASKELL previously declared at
Source(/Users/ja/dev/evm-semantics/tests/specs/lemmas.k) and
Location(259,1,339,10)
	Source(/Users/ja/dev/evm-semantics/tests/specs/lemmas.k)
	Location(273,1,359,10)
	    .	v~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	273 |	module LEMMAS-HASKELL [symbolic, kore]
	    |		...
	359 |	endmodule
```

The weird thing is that I didn't get this error when the profiling script ran the test. 
1) `make clean && make` doesn't fix this
2) I managed to fix this with `ulimit -n 10485760 && make tests/specs/bihu/collectToken-spec.k.prove -B`.

I also cannot run `build-prove`. This is the error that I'm getting:
```
kevm kompile --backend haskell                     \
	    edsl.md  \
	    --main-module EDSL         \
	    --syntax-module EDSL     \
	    -I /usr/lib/kevm/include/kframework -I /usr/lib/kevm/blockchain-k-plugin/include/kframework
/Library/Developer/CommandLineTools/usr/bin/make -C ./kevm_pyk venv-prod
. /Users/ja/dev/evm-semantics/kevm_pyk/venv-prod/bin/activate
. ./kevm_pyk/venv-prod/bin/activate && kevm solc-to-k tests/specs/examples/ERC20.sol ERC20 --verbose --definition .build/usr/lib/kevm/haskell --main-module ERC20-VERIFICATION > tests/specs/examples/erc20-bin-runtime.k
/Users/ja/dev/evm-semantics/kevm_pyk/venv-prod/bin/python3: No module named kevm_pyk.__main__; 'kevm_pyk' is a package and cannot be directly executed
make: *** [tests/specs/examples/erc20-bin-runtime.k] Error 1
```

`make kevm-pyk-venv` doesn't help. Any ideas?

**Comment by radumereuta** [comment]
@tothtamas28 can you help with the pyk issue here?

**Comment by ehildenb** [comment]
`make venv` should solve the `make build-prove` issue.

**Comment by fiedlr** [comment]
> `make venv` should solve the `make build-prove` issue.

I'm not seeing something... `venv` isn't a defined rule in the `Makefile`, i.e., `make venv` gives me `make: *** No rule to make target `venv'.  Stop.`

**Comment by tothtamas28** [comment]
Recently there have been changes in how we handle virtual environments. Can you point me to a commit so that I can check what configuration is in place there?

**Comment by fiedlr** [comment]
> Recently there have been changes in how we handle virtual environments. Can you point me to a commit so that I can check what configuration is in place there?

Thanks for your quick answer! HEAD is at commit `a3b8b0c9a107bf45dd85061dbd6ededfa7b0844d`, in the `tests-fix` branch.

**Comment by tothtamas28** [comment]
>  The weird thing is that I didn't get this error when the profiling script ran the test.

Is this possible you're trying to run the command with `./kevm`? It should be `./.build/usr/bin/kevm`.

> `venv` isn't a defined rule in the `Makefile`

Try `make kevm-pyk-venv` after `rm -rf ./kemv_pyk/venv-prod`.

Alternatively, pull the branch, and try `make venv` there (if it doesn't work, try `rm -rf ./.build/venv` first).

**Comment by fiedlr** [comment]
> > The weird thing is that I didn't get this error when the profiling script ran the test.
> 
> Is this possible you're trying to run the command with `./kevm`? It should be `./.build/usr/bin/kevm`.

I'm running it with `kevm` that is in PATH linked to `./.build/usr/bin/kevm`. However, it seems to be working now. I guess the issue was really in some wrong order of installation.

> 
> > `venv` isn't a defined rule in the `Makefile`
> 
> Try `make kevm-pyk-venv` after `rm -rf ./kemv_pyk/venv-prod`.
> 
> Alternatively, pull the branch, and try `make venv` there (if it doesn't work, try `rm -rf ./.build/venv` first).

1. didn't work
2. I pulled the branch,  ran `rm -rf ./.build/venv` and then `make venv` fails with: 

ERROR: deps/k/pyk is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).

`deps/k/pyk` doesn't even exist, so no surprise. This makes me wonder, isn't this because `make build-prove` needs local K deps instead of a global one?

**Comment by tothtamas28** [comment]
> This makes me wonder, isn't this because `make build-prove` needs local K deps instead of a global one?

Yes, the submodules have to be checked out and the dependencies built: https://github.com/runtimeverification/evm-semantics#build-dependencies.

**Comment by fiedlr** [comment]
Ok, that's new, because the `README.md` looks like it doesn't matter if I use the K submodule a global install. I've posted a PR updating the `README.md` here https://github.com/runtimeverification/evm-semantics/pull/1365/files

However, still no success. I did successfully 1. `make k-deps` 2. `rm -rf ./.build/venv` 3. `make venv`, all works, but now `make build-prove` gives me this:

```
ja@ja-mbp evm-semantics % make build-prove
. .build/venv/bin/activate
. .build/venv/bin/activate && kevm solc-to-k tests/specs/examples/ERC20.sol ERC20 --pyk --verbose --profile --verbose --definition .build/usr/lib/kevm/haskell --main-module ERC20-VERIFICATION > tests/specs/examples/erc20-bin-runtime.k
INFO 2022-09-08 12:16:01,795 kevm_pyk.solc_to_k - Running: solc --standard-json
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/ja/dev/evm-semantics/kevm-pyk/src/kevm_pyk/__main__.py", line 383, in <module>
    main()
  File "/Users/ja/dev/evm-semantics/kevm-pyk/src/kevm_pyk/__main__.py", line 33, in main
    execute(**vars(args))
  File "/Users/ja/dev/evm-semantics/kevm-pyk/src/kevm_pyk/__main__.py", line 89, in exec_solc_to_k
    solc_json = solc_compile(contract_file, profile=profile)
  File "/Users/ja/dev/evm-semantics/kevm-pyk/src/kevm_pyk/solc_to_k.py", line 252, in solc_compile
    process_res = run_process(['solc', '--standard-json'], logger=_LOGGER, input=json.dumps(args), profile=profile)
  File "/Users/ja/dev/evm-semantics/deps/k/pyk/src/pyk/cli_utils.py", line 65, in run_process
    res = subprocess.run(args, input=input, env=env, stdout=subprocess.PIPE, stderr=stderr, check=check, text=True)
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'solc'
0m2.458s 0m2.270s 0m0.148s python3 -m kevm_pyk solc-to-k tests/specs/examples/ERC20.sol ERC20 --definition .build/usr/lib/kevm/haskell --profile --main-module ERC20-VERIFICATION --definition .build/usr/lib/kevm/haskell -I /Users/ja/dev/evm-semantics/.build/usr/lib/kevm/include/kframework -I /Users/ja/dev/evm-semantics/.build/usr/lib/kevm/blockchain-k-plugin/include/kframework --verbose
make: *** [tests/specs/examples/erc20-bin-runtime.k] Error 1
```

**Comment by fiedlr** [comment]
> > This makes me wonder, isn't this because `make build-prove` needs local K deps instead of a global one?
> 
> Yes, the submodules have to be checked out and the dependencies built: https://github.com/runtimeverification/evm-semantics#build-dependencies.

Ok, this is new, because the README gives the impression that a global installation of K will do just fine for any purpose.
After building the deps, installing `poetry` and `solidity`, running `make venv`, I finally managed to get it working. I updated the `README.md` in this PR https://github.com/runtimeverification/evm-semantics/pull/1365/files, could you please have a look?
