### ISSUE TITLE
Record cheatcodes special parameters

### ISSUE THREAD

**Issue by JuanCoRo** [runtimeverification/evm-semantics#1370]
Cheatcodes like `prank`s, `expect`s and `boradcast`s appear on special functions such as [`call`](https://github.com/foundry-rs/foundry/blob/master/evm/src/executor/inspector/cheatcodes/mod.rs#L280) and [`end_call`](https://github.com/foundry-rs/foundry/blob/master/evm/src/executor/inspector/cheatcodes/mod.rs#L398), and have related structs structs such as [`Cheatcodes`](https://github.com/foundry-rs/foundry/blob/master/evm/src/executor/inspector/cheatcodes/mod.rs#L77), [`Prank`](https://github.com/foundry-rs/foundry/blob/master/evm/src/executor/inspector/cheatcodes/env.rs#L36), [`ExpectRevert`](https://github.com/foundry-rs/foundry/blob/master/evm/src/executor/inspector/cheatcodes/expect.rs#L28), etc.
We should include these structures/functionalities when encoding their related cheatcodes. See that #1349 is already going in that direction.

**Comment by anvacaru** [comment]
I'm going to close this issue for now. PRs like #1459 , #1448, #1436 add new subconfigurations for expected reverts, calls and events, to the `<foundry/>` K configuration, which is an extension of the `<kevm/>` configuration.
