### ISSUE TITLE
Foundry support user feedback

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/evm-semantics#1382]
From @kmbarry1:

- [ ] `foundry-kompile --regen` should be turned on by default, because users will usually call it after they need to call `forge build`.
- [ ] When a proof doesn't exist, you get an error which says `Unused filtering labels: [MODULE_NAME.test_name]`. It would be better to say something like "Tests not found: [ContractName.test_name]".
- [ ] Accidentally used `kevm` in root of repo, instead of in `.build/usr/bin`. Should make it harder to do this (move `*.md` K source files and `kevm` script into `src/` directory?)
- [ ] "glacially slow"

From @RaoulSchaffranek:

- [ ] `kevm foundry-prove` should auto-detect that `foundry-kompile` should be called on changes to compiled output: https://github.com/runtimeverification/evm-semantics/issues/1392#issuecomment-1258232770

From @lucasmt:

- [ ] New tests added to tests/foundry/test don't get added to the kcfgs.json file until foundry-kompile is run with the --reinit flag. This is not clear from the foundry.md file.
- [ ] Should omit the cells program, jumpDests, and code cell by default, or at least truncate them, in failing proof output.
- [ ] Calling `nix shell .#kevm` with a very simple change to `solc-to-k.py` ends up taking several minutes to rebuild. It should be instant (just a one-line change to a python file).

From @qian-hu:

- [ ] We should document that users should add `--verbose` to the `kevm` command when developing locally, because it's useful.

**Comment by lucasmt** [comment]
From @lucasmt:

- [ ] New tests added to `tests/foundry/test` don't get added to the `kcfgs.json` file until `foundry-kompile` is run with the `--reinit` flag. This is not clear from the `foundry.md` file.

**Comment by anvacaru** [comment]
- The byte strings outputted are hard to read most of the time. In particular, for KEVM, we should output hexadecimal strings.
   -  I want to select code in the debugger. Currently, I cannot make any selection to copy-paste. If I need to copy an address, I will exit the debugger and use `foundry show` on a specific node to output the configuration and copy the address from there.
   -  Whenever I have a custom assumption inserted with `vm.assume()` , I do not see it in the kcfg.

**Comment by lucasmt** [comment]
> The byte strings outputted are hard to read most of the time. In particular, for KEVM, we should output hexadecimal strings.

Adding to this, a problem we've run into before is that the value `32` (`0x20`) is displayed as a space in ASCII. This makes it very hard to tell that it's there. This is especially problematic since a length of 32 bytes is so common in KEVM.

**Comment by ehildenb** [comment]
@Scott-Guest:

- First, do the Foundry demo: https://github.com/runtimeverification/foundry-demo/ to learn about the KCFG visualizer.
- Then, see if you can fix the issue with not being able to select text from the TUI: https://github.com/runtimeverification/pyk/blob/master/src/pyk/kcfg/tui.py. You can get support for the library Textualize that we're using here: https://discord.gg/jPvvrHqb

**Comment by Scott-Guest** [comment]
@anvacaru @ehildenb To select text in the debugger, try holding SHIFT or OPTION while selecting. This works on my machine.

Quoting the [Textualize FAQ](https://github.com/Textualize/textual/blob/main/FAQ.md#how-can-i-select-and-copy-text-in-a-textual-app):

> Running a Textual app puts your terminal in to application mode which disables clicking and dragging to select text. Most terminal emulators offer a modifier key which you can hold while you click and drag to restore the behavior you may expect from the command line. The exact modifier key depends on the terminal and platform you are running on.
> - iTerm Hold the OPTION key.
> - Gnome Terminal Hold the SHIFT key.
> - Windows Terminal Hold the SHIFT key.
>
> Refer to the documentation for your terminal emulator, if it is not listed above.

We should document this so no one else runs into the same issue, but I don't think any action beyond that is necessary.

**Comment by ehildenb** [comment]
Let's add documentation here: https://github.com/runtimeverification/evm-semantics/blob/master/include/kframework/foundry.md#available-commands

And here: https://github.com/runtimeverification/evm-semantics/blob/master/VERIFICATION.md#more-to-know
