### ISSUE TITLE
Include solc in runtimeverificationinc/runtimeverification-evm-semantics docker image

### ISSUE THREAD

**Issue by enzoevers** [runtimeverification/evm-semantics#1385]
When trying to run `solc-to-k` in  [runtimeverificationinc/runtimeverification-evm-semantics:ubuntu-focal-master](https://hub.docker.com/r/runtimeverificationinc/runtimeverification-evm-semantics/tags) I get an error that `solc` cannot be found. And indeed, when going into the container solc is not installed.

If I'm not mistaking, [package/docker/Dockerfile.ubuntu](https://github.com/runtimeverification/evm-semantics/blob/5ec6128ca399dc770eb1ae32bb5dd3baeb6152e5/package/docker/Dockerfile.ubuntu) is the dockerfile used to create this docker image (looking at the [Jenkins](https://github.com/runtimeverification/evm-semantics/blob/96392cc2f4ec1ae593a0fa71dfdd0bcd1cac6fcc/Jenkinsfile#L133) file).

Could `solc` be installed in this image too so that `solc-to-k` works out of the box?

Or should `solc` be part of the `Depends` section in [control.focal](https://github.com/runtimeverification/evm-semantics/blob/5ec6128ca399dc770eb1ae32bb5dd3baeb6152e5/package/debian/control.focal#L13)?

**Comment by anvacaru** [comment]
We should copy this line from the main Dockerfile https://github.com/runtimeverification/evm-semantics/blob/5ec6128ca399dc770eb1ae32bb5dd3baeb6152e5/Dockerfile#L11

**Comment by omarzd** [comment]
Hi. I get this same error. I followed the README today, so my build should include the fix, right @anvacaru? Here is a dump from my terminal:
```
(venv) omarzd@PC:~/evm-semantics$ make build-prove
. .build/venv/bin/activate
. .build/venv/bin/activate && kevm solc-to-k tests/specs/examples/ERC20.sol ERC20 --pyk --verbose --profile --verbose --definition .build/usr/lib/kevm/haskell --main-module ERC20-VERIFICATION > tests/specs/examples/erc20-bin-runtime.k
INFO 2022-11-03 17:46:25,278 kevm_pyk.solc_to_k - Running: solc --standard-json
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/omarzd/evm-semantics/kevm-pyk/src/kevm_pyk/__main__.py", line 617, in <module>
    main()
  File "/home/omarzd/evm-semantics/kevm-pyk/src/kevm_pyk/__main__.py", line 45, in main
    execute(**vars(args))
  File "/home/omarzd/evm-semantics/kevm-pyk/src/kevm_pyk/__main__.py", line 96, in exec_solc_to_k
    solc_json = solc_compile(contract_file, profile=profile)
  File "/home/omarzd/evm-semantics/kevm-pyk/src/kevm_pyk/solc_to_k.py", line 303, in solc_compile
    process_res = run_process(['solc', '--standard-json'], logger=_LOGGER, input=json.dumps(args), profile=profile)
  File "/home/omarzd/evm-semantics/.build/venv/lib/python3.8/site-packages/pyk/cli_utils.py", line 80, in run_process
    res = subprocess.run(args, input=input, env=env, stdout=stdout, stderr=stderr, check=check, text=True)
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'solc'
0m1.422s 0m1.306s 0m0.089s python3 -m kevm_pyk solc-to-k tests/specs/examples/ERC20.sol ERC20 --definition .build/usr/lib/kevm/haskell --profile --main-module ERC20-VERIFICATION --definition .build/usr/lib/kevm/haskell -I /home/omarzd/evm-semantics/.build/usr/lib/kevm/include/kframework --verbose
make: *** [Makefile:524: tests/specs/examples/erc20-bin-runtime.k] Error 1
```

**Comment by anvacaru** [comment]
@omarzd It looks like the PR I opened did not fix the problem. I will reopen this for now. Thank you for pointing it out!

**Comment by anvacaru** [comment]
We are not supporting the docker images anymore. We now have a one click install for kevm called `Kup` [link here](https://github.com/runtimeverification/kup/). Does the issue replicate with this way of installation?
