### ISSUE TITLE
kevm docker `[Error] Outer Parser: Module <module name> previously declared at`

### ISSUE THREAD

**Issue by enzoevers** [runtimeverification/evm-semantics#1390]
When running the kevm docker with tag [ubuntu-focal-0e96c8d](https://hub.docker.com/layers/runtimeverificationinc/runtimeverification-evm-semantics/ubuntu-focal-0e96c8d/images/sha256-7ae7b8fece78a2ce4fd40f389a61a0814d40f770155c70b8cdcf25cdbc6a0cd4?context=explore) with `kevm prove` it gives me the several errors that all look like the following: 

```bash
[Error] Outer Parser: Module WORD previously declared at
Source(/home/jenkins-runner/workspace/KEVM_master/focal-build/.build/usr/lib/kevm/include/kframework/word.md)
and Location(7,1,336,10)
	Source(/usr/lib/kevm/include/kframework/word.md)
	Location(7,1,336,10)
	    .	v~~~~~~~~~~
	  7 |	module WORD
	    |		...
	336 |	endmodule
	    .	~~~~~~~~^
```

while `find / -name 'word.md'` results in only:

```bash
/usr/lib/kevm/include/kframework/word.md
```

Does anyone know to resolve this?

I created a project similar to the [ERC20](https://github.com/runtimeverification/evm-semantics/blob/0e96c8d5d6bed3a131ed2ed8eedaa873ddef9236/tests/specs/examples/erc20-spec.md) example and then I ran it with:

```bash
sudo docker run -v $PWD/example-smart-contracts:/prj runtimeverificationinc/runtimeverification-evm-semantics:ubuntu-focal-0e96c8d bash -c "kevm prove --backend haskell /prj/kevm/VeriToken-spec.md --verif-module VERITOKEN-SPEC"
```

**Comment by enzoevers** [comment]
Initially, I was logged in to another (not my main) account when creating a similar issue https://github.com/runtimeverification/k/issues/2910 issue.  That is why I closed it and created this issue with my main account. My previously closed issue was transferred to the k repository where it was answered.

Sorry for the inconvenience. Thank you for taking this up.

**Comment by ehildenb** [comment]
@enzoevers we'll close this for now, please re-open if it's still an issue.
