### ISSUE TITLE
kevmup a dependency and project manager for kevm

### ISSUE THREAD

**Issue by RaoulSchaffranek** [runtimeverification/evm-semantics#1392]
# kevmup

This document describes a potential new command-line tool called kevmup (the name is just a working title) to enhance the user experience when working on a project that uses kevm for verification. The tool covers the entire project life cycle. `kevmup` is akin to what stack is for Haskell, pip for Python, or npm for JavaScript.

Notice that there are currently several other active efforts. 

## Related issues

https://github.com/runtimeverification/pyk/issues/30
https://github.com/runtimeverification/k/issues/2894
https://github.com/runtimeverification/k/issues/2886

## Features

kevmup offers a streamlined way to assist the following activities:

* Bootstrap kevm-projects: create k-modules from Solidity source files
* Good support for Foundry: create k-modules from Foundry tests
* Install and update KEVM locally (including all transitive dependencies)
* Run k-proofs

## Creating a new kevm project

Setting up a new kevm project should be a minimal configuration process. Ideally, it should be zero-configuration, but that may be too optimistic. However, we should follow a radical convention-over-configuration path. In the bottom line, it saves users time to think about project structure. Also, it may be harder to apply something you’ve learned from a different project (or tutorial) to your own project when the structures are vastly different. On the other hand, if all projects follow roughly the same structure, it is much easier to transfer knowledge between them.

However, we may have to account for some flexibility in project structure and may need to introduce a couple of configuration options. For example, we cannot assume that `kevmup` can always be run from the project root folder.

## Initializing a new kevm project

~~~sh
kevmup init

~~~

This command initializes a fresh k-project inside the folder from where it was called. This process comprises the following steps:

* Create a local configuration file to store project metadata, e.g., the required KEVM version.
* Download and install a local instance of the latest KEVM version. This has exactly the same effect as 
running `kevmup install`
* Detect relevant Solidity source files and bootstrap k-definition files. This has exactly the same effect as running `kevmup bootstrap`

## Installing KEVM

~~~sh
kevmup install

~~~

The command reads, downloads, and installs the required kevm version from the project configuration file. The installation is not system-wide but local to the project folder. We do not need to add `kevm` or any other binary on the user's `$PATH` variable. Instead, the user should use `kevmup prove` or `kevmup kevm` commands to interact directly with `kevm`.

If there is no project configuration file in the current working directory, the command should ask the user if he wants to run it now.

## Bootstrapping

~~~sh
kevm bootstrap
~~~

Generate k-modules for each Solidity source file. If we detect a foundry test suite, we should also generate k-modules for each foundry test file. For each source file, we should generate two files: One that is meant to be edited by the user and one that can be re-generated safely when the source-file changes. The generated user file should contain a "hello world" claim so that the user knows where to put his claims.

## Updating KEVM

~~~sh
kevmup update

~~~

Update the kevm version inside the project configuration file and download and install the latest version locally. This should have the same effect us manually updating the kevm version inside the project configuration file and then running `kevmup install`. Notice, that we may need to deal with backward incompatibilities.

## Running proofs

~~~sh
kevmup prove

kevmup proof
~~~

Automatically detect all verification modules and run the kevm prover. The output should be a nice report similar to the one from `foundry test`.

## Interacting with `kevm` directly.

~~~sh
kevmup kevm
~~~

In some cases, a user may want to get finer control over `kevm`. He can then use the `kevmup kevm` command to interact directly with the project-specific `kevm` installation. Alternatively, we may think of a command `kevmup sh` that creates a new shell, where the local kevm installation is on the `$PATH`.

## Clean-up

~~~sh
kevmup clean
~~~

Delete all artifacts produced by `kevmup`. By default, this should NOT delete the generated k-modules meant for manual editing.

## Selfupdating kevmup

~~~sh
kevmup self-update
~~~

Update `kevmup` itself to the latest version. Ideally, the user should not be forced to restart as shell.

## Installation / Self-Updating / Uninstalling

This section is about installing, updating and uninstalling `kevmup` itself and not about `kevm`.

Good usability starts even before we think of a project lifecycle. Usability starts with installing the kevmup tool and ends with its uninstallation.

The end user shouldn’t be forced to run manual installation steps beyond the bare minimum. Installing kevmup should be a zero-configuration process. Ideally, the user would go to a website, download a binary executable and be ready to go. Alternatively, we can also think of a thin installation script that makes kevmup system-wide available.

We should avoid making permanent changes to a globally installed kevmup instance; this includes system-wide configuration options. The problem with permanent changes is that users tend to forget about them. They pile up and eventually lead to unexpected problems. They’re hard to reproduce and difficult to debug. Even worse, people avoid updating or re-installations because they don’t want to lose their configuration. Users should be able to rely on kevmup, knowing that it will always work the same, whether it’s a fresh installation or an old one from 2 years ago. They should feel confident to re-install the tool at any point in time without fearing losing any customizations.

Like every tool, kevmup will be updated from time to time. Installation of a newer version over an old version should seamlessly replace the old one. In addition, we should offer a `kevmup self-update` command that automatically updates to the latest version. Again, this should be a zero-configuration process. Of course, everything that worked before should work after the update, or we will lose the user’s trust. However, breaking changes are not always avoidable. In these cases, we should at least offer clear documentation about what needs to be done to get the newer version working with projects created with an older version. When introducing breaking changes, we should consider the following questions: Is this breaking change really necessary? Can we detect and report incompatibilities of projects created with older versions of kevmup? Can we automatically fix them? If not, give detailed instructions on what needs to be done manually and where to seek help. Notice that every breaking change inevitably leads to a bad user experience and loss of trust. That is, it must be justified by good arguments. This also means that features should be designed with backward- and forward-compatibility in mind. 

Finally, we should offer a seamless uninstallation method that does not leave any traces on the user's system. This is important because users are likelier to try a tool if they know their system will be untouched if the experiment fails. A user who has had a bad experience uninstalling a tool may not consider installing it a second time.

**Comment by ehildenb** [comment]
`kevmup` should basically be a bash script which wraps the Nix commands needed to do the same. Similar to how we'll have `kup` wrap the Nix commands for interacting with K versions. I like the name, so I'll modify that issue to be the same.

**Comment by ehildenb** [comment]
We should focus `kevmup` on just installing `kevm` though, similar to how `rustup` just installs `rustc` and `fonudryup` installs `fonudry`.

So commands like `prove` or `proof` don't amke sense here. Those wolud still be via `kevm ...`.

**Comment by RaoulSchaffranek** [comment]
The idea behind the `prove` command was to have a one-liner, that automatically detects all k-specifications inside the project folder and attempts to proof them. The idea was born when I recently had to assemble the following command to run a proof:

~~~
kevm kompile \
    --backend haskell \
    specs/LSP7DigitalAsset-spec.k \
    --definition specs/verification/haskell \
    --main-module VERIFICATION \
    --syntax-module VERIFICATION \
    -I /usr/lib/kevm/include/kframework \
    -I /usr/lib/kevm/blockchain-k-plugin/include/kframework
kevm prove \
    --backend haskell \
    specs/LSP7DigitalAsset-spec.k \
    --definition specs/verification/haskell
~~~

With the new `foundry-kompile` and `foundry-prove` the situation has improved significantly. The new commands now look like this: 

~~~
forge build
kevm foundry-kompile out --regen --rekompile --reinit
kevm foundry-prove out
~~~

This is much better, but contrast this with the simplicity of running a foundry test: When I run `forge test`, it will automatically build the Solidity files that are necessary for the tests and it would even download all dependencies from npm automatically. I can literally run `git clone` and then `forge test` without having to learn anything about the project structure. I want our process to be as simple as that.

The other reason to have `kevmup` wrap around `kevm` was that a user can have multiple versions of `kevm` installed at the same time, and `kevmup` would choose the correct version for the underlying project automatically.

**Comment by ehildenb** [comment]
Anything that is abotu actually running the tool should be built into the `kevm` command, and defaults that make it easier should be put there.

But Sam has a prototype of `kup` now that also even just handles KEVM versions smoothly, along with K versions, so you can have multiple semantics installed and such (or at least, it's attempting to do that, modulo some bugs we'll iron out): https://runtimeverification.slack.com/archives/C7E701MFG/p1664227496058109?thread_ts=1663938750.906789&cid=C7E701MFG

So we can tell people for installing KEVM to do:

```
bash <(curl https://kframework.org/kup)
kup install kevm
```

Then do any `kevm` commands like `kevm foundry...`.

I do agree that `kevm foundry-prove` should just auto-detect if `kevm foundry-kompile...` needs to be run. What needs to happen is that [here in `exec_foundry_prove`](https://github.com/runtimeverification/evm-semantics/blob/master/kevm-pyk/src/kevm_pyk/__main__.py#L303), we should inspect the contents of the `foundry_out` directory and somehow hash them, and store that hash in `foundry_definition_dir` as a file. If the hash changes, we re-run `exec_foundry_kompile`, and let it deal with regenerating everything needed.

**Comment by ehildenb** [comment]
BTW, foundry interface feedback can go here, I've recorded this one there: https://github.com/runtimeverification/evm-semantics/issues/1382. You can comment or edit the main issue body. Once there is a bit more feedback, I'll go through and triage it a bit.

**Comment by anvacaru** [comment]
@RaoulSchaffranek should we keep this issue open or does the Kup cover this as well? https://github.com/runtimeverification/k/blob/master/k-distribution/INSTALL.md#fast-installation

**Comment by RaoulSchaffranek** [comment]
@anvacaru I need to look at Kup, but I don't have the time right now. So please, let's keep this issue open.

**Comment by ehildenb** [comment]
@RaoulSchaffranek I think that there are already plans for `kup` and `kbuild` to do everything asked here, so I'd prefer to close this in favor of the `kup` commands.

Also, I'm using `kup` directly on my machine for building and running kevm, and it's working for Foundry verification.

**Comment by RaoulSchaffranek** [comment]
I tried `kup` and it worked like a charm. Some other features described here that are not handled by `kup` overlap with `foundry` and are better handled there.
