### ISSUE TITLE
`foundry.md` cleanups

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/evm-semantics#1397]
- [x] No cell-map lookups against keys that are defined via constraints in side-condition: https://github.com/runtimeverification/evm-semantics/pull/1364#discussion_r978719322
- [x] Formatting in several places.
- [x] Contextual functions for the getters (eg. `getNonce`).

**Comment by anvacaru** [comment]
Addressed these changes in https://github.com/runtimeverification/evm-semantics/pull/1404.
