### ISSUE TITLE
Lightweight fork mainnet option needed

### ISSUE THREAD

**Issue by RaoulSchaffranek** [runtimeverification/evm-semantics#1401]
Some of OpenZeppelin's contract constructors (and initializers) depend on external calls. For example the ERC777 implementation registers itself at a hardcoded ERC1820 registry:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fb9345814b5a0e8cfc7ccb6210855d47e0e65e57/contracts/token/ERC777/ERC777.sol#L74-L75

When we want to test such a contract with Foundry we need to use the `--fork-url` parameter to fetch the mainnet state. If we omit this step, we cannot even deploy a local copy of the contract.

When we want to verify such a contract with KEVM, we can workaround this by manually updating the ` <accounts>`- cell.

Given the popularity of OpenZeppelin's contracts, let us aim for a simplified process and maybe offer a lightweight "fork mainnet" feature. For a start, I think it would be enough to have a pyk-command that can fetch the bytecode+state from a given address and generate a helper module.

**Comment by ehildenb** [comment]
@RaoulSchaffranek is this still needed? It seems to me that we could probably workaround this by just pulling in the Solidity code of the contract we want to pull from mainnet directly?

Or is the point that the mainnet code may be changing (eg. via a proxy pattern), and so when that happens, we want to reverify the property tests against the updated mainnet state?

**Comment by RaoulSchaffranek** [comment]
@ehildenb 
We can pull the code manually from Etherscan. The problem is how do we tell KEVM about it? When working with KEVM directly, we can add the contract code and storage to the `<accounts>`-cell. But, with KEVM+Foundry, we don't have the flexibility to edit the `<accounts>`-cell in a straightforward way - only with some hackery. Or maybe I don't know how to do it.

@andreiburdusa 
Do we support the [etch](https://book.getfoundry.sh/cheatcodes/etch) cheat code? This could be a simple workaround.

**Comment by RaoulSchaffranek** [comment]
Ups, sorry! Damn autofill.

**Comment by anvacaru** [comment]
Yes, we are supporting the `etch` cheat code.

**Comment by RaoulSchaffranek** [comment]
Awesome! I'll close this issue then. Thank you!
