### ISSUE TITLE
More detailed expectCall* cheatcodes

### ISSUE THREAD

**Issue by anvacaru** [runtimeverification/evm-semantics#1444]
We should add cheatcodes for all possible calls
- expectDelegateCall
- expectCallCode
- expectStaticCall
- expectCall
- expectNoCall

**Comment by anvacaru** [comment]
- `expectStaticCall`, `expectRegularCall`, `expectDelegateCall`, `expectCreate`, `expectCreate2` - #1448

**Comment by anvacaru** [comment]
**TO DO:**
 - Implement `expectNoCall`. 
 - Implement  `expectCall` from foundry book. Here we can add another value to the `OpcodeType` sort named `AnyCall`, which will match with any `CALL*` opcode rule.

**Comment by ehildenb** [comment]
We have the whitelist cheatcodes now, which can be used to assert that certain accounts are not accessed, or how they are allowed to be accessed.
