### ISSUE TITLE
Constrain `ACCOUNTS_INIT` variable for foundry tests

### ISSUE THREAD

**Issue by RaoulSchaffranek** [runtimeverification/evm-semantics#1481]
When we generate a specification from a foundry test, the `<accounts>`-rewrite-rule looks similar to the following:

~~~xml
<accounts>
  ( <account>
    <acctID>
      1032069922050249630382865877677304880282300743300
    </acctID>
    ...
  </account>
  ...
  ( _ACCOUNTS_INIT => ?_ACCOUNTS_FINAL ) )
</accounts>
~~~

When we run a proof, the prover will add the following side condition to the final configuration:

~~~k
#And
  {
    false
  #Equals
    <acctID>
      1032069922050249630382865877677304880282300743300
    </acctID> in_keys ( _ACCOUNTS_INIT )
  }
~~~

Notice that `_ACCOUNTS_INIT` is unconstrained in the specification but constrained in the final configuration. Hence, we get the following error message:

~~~
The configuration's term unifies with the destination's term, but the implication check between the conditions has failed.
~~~

Can we automatically generate the necessary constraints to the `_ACCOUNTS_INIT`-variable to not include any of the addresses mentioned in the surrounding `<accounts>`-context?

As a workaround, I replaced `_ACCOUNTS_INIT` with `.Bag` in my specification, but it would be nice if we could be more general.

**Comment by anvacaru** [comment]
I'm closing this because of the comments from #1482.
