### ISSUE TITLE
Installation instructions are badly out of date

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/evm-semantics#1536]
The installation instructions for any given project should include the best ways for users to install the project, as well as accurate instructions about how to build the project from source and what the dependencies and supported platforms are. Instead, we are recommending users install a three month old version of the project, and the project does not build at all on Ubuntu Focal or Debian stable. And yet, the README explicitly mentions support for both Ubuntu Bionic and Ubuntu Focal.

**Comment by ehildenb** [comment]
We also need to require Poetry > 1.3.
