### ISSUE TITLE
Poetry `git` dependency to `kevm-pyk` is broken

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/evm-semantics#1649]
~Blocked on: https://github.com/runtimeverification/evm-semantics/issues/1658~

---

When adding

```
kevm-pyk = { git = "https://github.com/runtimeverification/evm-semantics.git", subdirectory = "kevm-pyk", rev = ... }
```

to a dependent project, `poetry install` fails with

```
No git repository was found at ../../pybind/pybind11
```

The error comes from the `k` submodule and is caused by a [Poetry bug ](https://www.github.com/python-poetry/poetry/issues/6499). But even after it's fixed (probably in the next Poetry release, 1.4.2), there is the issue of slow installation due to Poetry recursively cloning submodules.

Fixes for both issues include:
* Extract `kevm-pyk` to its own repository
* Drop the `k` submodule: https://github.com/runtimeverification/evm-semantics/issues/1658

Workarounds:
* Use submodules in dependent projects (like e.g. [ksummarize](https://github.com/runtimeverification/ksummarize)). This makes installation of / dependence on the dependent module really cumbesome though.

**Comment by ehildenb** [comment]
We can probably drop the K submodule, and instead use `kup` to install K dependency.

**Comment by tothtamas28** [comment]
> The error comes from the `k` submodule and is caused by a Poetry bug

It seems to work with Poetry 1.5.1.

> But even after it's fixed (...), there is the issue of slow installation due to Poetry recursively cloning submodules.

It is still slow (3 minutes or so).

**Comment by yale-vinson** [comment]
@tothtamas28 Is improving this performance something we should add to the Kontrol backlog, or is it as good as it's going to get? 

I would like to add something specific to the Backlog if there is a clear path forward, or if it requires some investigation first we can move it there until we get a bead on what we can do to improve performance if possible.

**Comment by tothtamas28** [comment]
We can improve on this by eliminating the `plugin` submodule ([`blockchain-k-plugin`](https://github.com/runtimeverification/blockchain-k-plugin)) from this repository. How I see it we have two options:
1. Put the responsibility of installing the corresponding native dependencies on the user. Support this with documentation and instructive error messages on kompilation failure.
2. Distribute `blockchain-k-plugin` along with its compiled native dependencies as a Python wheel. Care must be taken not to violate the license terms of these dependencies.

**Comment by yale-vinson** [comment]
@tothtamas28 This issue is pretty stale, but I get there have been other things that are higher priority to address. Should we keep this open and in the backlog? Trying to do some cleanup, and happy to leave it where it is if there is value in it.
