### ISSUE TITLE
`kevm interpret --debugger` not working correctly

### ISSUE THREAD

**Issue by anvacaru** [runtimeverification/evm-semantics#1670]
Nothing is displayed when `--debugger` flag is passed to `kevm interpret`. 
I've tried inputting `step` and got the response `The program is not being run`. 
Seems that the debugger is running but all the output is redirected somewhere else.
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/16517508/228190350-0af2f574-056a-4201-b46a-7b77dec02c93.png">

**Comment by anvacaru** [comment]
After debugging with @radumereuta, we found the following:
   1. we need to specify a way to enable `--enable-llvm-debug` in `kevm-pyk`, maybe add a new option `--kopts ARGS` to pyk so we can manually add new options that are not supported by pyk yet. 
   2. the `kevm` script is redirecting the output to a temp file [here](https://github.com/runtimeverification/evm-semantics/blob/master/bin/kevm#L215). We should add support for `--debugger` flag to stop hiding the output.
  
krun should fail when --debugger is provided but the definition is not kompiled with debug symbols. (`--enable-llvm-debug` or `-g -O1`)

**Comment by tothtamas28** [comment]
> we need to specify a way to enable `--enable-llvm-debug` in `kevm-pyk`, maybe add a new option `--kopts ARGS` to pyk

I'd rather not add such a blanket parameter, because it makes working around missing flags very convenient for downstream projects. Too many such flags and we lose the benefits of the additional layer. Instead, people should just open an issue or PR on `pyk` for the missing feature, helping the tool evolve in the right direction.
