### ISSUE TITLE
Error in `foundry-kompile` when requiring a file from a different directory

### ISSUE THREAD

**Issue by lucasmt** [runtimeverification/evm-semantics#1676]
Calling `kevm foundry-kompile` with `--requires path/to/file.k` causes it to try to copy the file to `out/kompiled/path/to/file.k`, producing the following error because the subdirectory `out/kompiled/path/to` doesn't exist:
```
INFO 2023-03-29 11:46:32,959 kevm_pyk.foundry - Copying requires path: path/to/file.k -> out/kompiled/path/to/file.k
Traceback (most recent call last):
  File "/nix/store/blpq09nlz80qg972zcd20x0g3bgl5h7l-python3.10-kevm-pyk-1.0.63/bin/.kevm-pyk-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/blpq09nlz80qg972zcd20x0g3bgl5h7l-python3.10-kevm-pyk-1.0.63/lib/python3.10/site-packages/kevm_pyk/__main__.py", line 62, in main
    execute(**vars(args))
  File "/nix/store/blpq09nlz80qg972zcd20x0g3bgl5h7l-python3.10-kevm-pyk-1.0.63/lib/python3.10/site-packages/kevm_pyk/__main__.py", line 211, in exec_foundry_kompile
    foundry_kompile(
  File "/nix/store/blpq09nlz80qg972zcd20x0g3bgl5h7l-python3.10-kevm-pyk-1.0.63/lib/python3.10/site-packages/kevm_pyk/foundry.py", line 229, in foundry_kompile
    shutil.copy(req, req_path)
  File "/nix/store/xzyq7h4cmjkr596010w5x6icrc918cgr-python3-3.10.9/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/nix/store/xzyq7h4cmjkr596010w5x6icrc918cgr-python3-3.10.9/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'out/kompiled/path/to/file.k'
```
Furthermore, if the path to the file is something like `../../file.k`, it will copy the file to `out/kompiled/../../file.k`, which is outside of the `out` directory. If we need to have a copy of the file in `out/kompiled`, it seems to me that we would want to copy without the path, or at least to something like `path_to_file.k` if we want to be able to disambiguate between different files with the same name.

**Comment by nwatson22** [comment]
Are there any current examples available of `foundry-kompile --require` being used, so I can make sure an implementation of this would make sense for those contexts?

**Comment by lucasmt** [comment]
@nwatson22 You can find an example here: https://github.com/runtimeverification/_audit_Lukso_07292426-ab46-4492-adcd-4bd34d864353/tree/path-issue. You can reproduce the error by doing
```
bash lsp-foundry/set-up-foundry.sh
bash reproduce-proofs.sh
```
It should give you the following message:
```
FileNotFoundError: [Errno 2] No such file or directory: 'lsp-foundry/out/kompiled/lsp-foundry/lukso-lemmas.k'
```

**Comment by ehildenb** [comment]
Users problem if they try to include files with the same name, we should just be taking the basename of the file.

We can warn them about it potentially? By having the list of files that KEVM has by default `evm.md`, `evm-types.md`, etc.., and checking if any copied into place conflict with each other or with that list? But only if it's really easy to implement that, otherwise I think it's just user error.

**Comment by nwatson22** [comment]
The system I have now uses a subdirectory `kompiled/requires` to store all the user `--require`ed files, and warns about duplicate names among those, but shouldn't have to worry about conflicting with the default KEVM files.
