### ISSUE TITLE
Installs for KEVM

### ISSUE THREAD

**Issue by reekamaharaj** [runtimeverification/evm-semantics#1680]
Integrate kore-rpc install to kevm without having to install k. 

Would this be installing kore-rpc explicitly or making changes to kevm to include kore-rpc?

**Comment by ehildenb** [comment]
We'd like to not have to do `kup install k` or `kup install kore-rpc` to use the `kevm`. @reekamaharaj you can work with @goodlyrottenapple to make that happen.

**Comment by goodlyrottenapple** [comment]
I believe `kore-rpc` is already on PATH for the `kevm` binary. @reekamaharaj can you confirm which command is failing for you when the kore-rpc/k package is not installed?

**Comment by reekamaharaj** [comment]
I ran everything in the foundry demo and it looks like you can just install kevm and everything works as expected. SO I think we can close this issue. And I will update the blog post to removed the k and kore-rpc install instructions. The ReadMe for KEVM will also need to be updated to take those steps out.
