### ISSUE TITLE
Raise a warning instead of an error in _get_method_abi(mname)

### ISSUE THREAD

**Issue by anvacaru** [runtimeverification/evm-semantics#1683]
The function 
```python
        def _get_method_abi(_mname: str) -> Dict:
            for _method in contract_json['abi']:
                if _method['type'] == 'function' and _method['name'] == _mname:
                    return _method
            raise ValueError(f'Method not found in abi: {_mname}')
```
raises an error if the `_mname` function is not found in the `abi` of a contract.

We've discovered an edge case in which the compiled output does not have an abi for the function `config()`.

```json
  "abi": [],
  "bytecode": {
    "object": ["..."],
    "sourceMap": "...",
    "linkReferences": {}
  },
  "deployedBytecode": {
    "object": "...",
    "sourceMap": "...",
    "linkReferences": {}
  },
  "methodIdentifiers": {
    "config()": "79502c55"
  },
```

While investigating what's the cause of this, we should also modify the function to return a warning instead and skip the function.

**Comment by anvacaru** [comment]
Hmm, it looks like #1667 overwritten #1687.

**Comment by nwatson22** [comment]
> Hmm, it looks like #1667 overwritten #1687. This should include a test as well.

Apologies, I merged it poorly. I've added another PR which should hopefully get the old behavior back.
