### ISSUE TITLE
msg.sender address in initial state

### ISSUE THREAD

**Issue by anvacaru** [runtimeverification/evm-semantics#1691]
Currenty, the KEVM configuration is initialized with a symbolic `CALLER_ID` instead of the address that Foundry uses as `msg.sender`. Perhaps we should include that account in the initial account state and set the concrete message sender.

**Comment by ehildenb** [comment]
Here is where in the code the `msg.sender` and `msg.origin` are set: https://github.com/runtimeverification/evm-semantics/blob/8960441a7bf0b9961833a47ad72826cd17792f19/kevm-pyk/src/kevm_pyk/foundry.py#L1005

**Comment by ehildenb** [comment]
We can use the pranks to set these in the test.
