### ISSUE TITLE
Output information on path feasibility on failed proof

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/evm-semantics#1700]
From the presentation with Palina, it looks like most tools focus on providing concrete path inputs to find the assertion violations for the user.

We can do this in multiple parts:

- [ ] First variant: when proofs are failing, print out a more informative summary of the failure than what we currently are. This would include:
  - For each failing node, is it a frontier node? (so depth bound reached)
  - If it's a stuck node, print out the path condition that reaches that stuck point.
- [ ] Second variant: once we have the more informative output, also check that stuck nodes are actually feasible. This means:
  - Send the path condition of the stuck node to Z3 and ask for a model.
  - Maybe we do this by making a new RPC endpoint for Haskell backend to get models back?

**Comment by nwatson22** [comment]
What do you mean by the path condition? Is it just the constraint on the stuck node? I've been trying to think of ways to show something more informative than that, but I'm running up against some walls. It would be nice to show which assertions are being violated, but if I'm correct, we aren't dealing with the assertions directly but rather they're just compiled to EVM bytecode that will fail if the assertion is violated.

It would be cool if we could print out the source locations of violated assertion and the conditions that caused it to be violated. One thing I have tried so far is just outputting all the constraints accumulated from Splits, but that only gives the relevant condition for some cases.
