### ISSUE TITLE
Interactive debugger not working anymore

### ISSUE THREAD

**Issue by anvacaru** [runtimeverification/evm-semantics#1701]
```
== kevm: KEVM Version
1.0.76
```
Steps:
```bash
kup install kevm
cd $KEVM/tests/foundry
forge build
kevm foundry-kompile -v
kevm foundry-prove --test StoreTest.testLoadNonExistent -v
kevm foundry-view-kcfg StoreTest.testLoadNonExistent
```
Running the interactive debugger on any proof results in this empty screen.

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/16517508/230307654-74ab5235-8f71-4a09-8aaa-b15d0d7c223f.png">

*edit*: `foundry-list` and `foundry-show` are not working anymore as well.

**Comment by tothtamas28** [comment]
I was able to reproduce this on a source build ([v1.0.76](https://github.com/runtimeverification/evm-semantics/tree/v1.0.76)).

**Comment by anvacaru** [comment]
The issue has been introduced in this commit [`5f2345d8ac7bc7138693033904fe00e03bde64f9`](https://github.com/runtimeverification/evm-semantics/commit/5f2345d8ac7bc7138693033904fe00e03bde64f9).
