### ISSUE TITLE
`foundry-kompile` will throw an error for functions named with K reserved names

### ISSUE THREAD

**Issue by anvacaru** [runtimeverification/evm-semantics#1703]
Functions named after K reserved names, such as `claim`, will cause `foundry-kompile` to throw an error.

Contract example 
```solidity
contract TestNumber is DSTest{
    uint256 public testNumber ;

    constructor(uint256 initial){
        testNumber = initial;
    }

    function t(uint256 a) public returns (uint256) {
        uint256 b = 0;
        testNumber = a;
        emit log_string("here");
        return b;
    }

    function claim(uint256 a) public {}

}
```

error 
```bash
[Error] Inner Parser: Parse error: unexpected end of file following token '.'.
        Source(/home/anvacaru/rv/evm-semantics/tests/foundry/out/kompiled/foundry.k)
        Location(5104,25,5104,25)
        5104 |      rule  ( TestNumber . claim ( V0_a ) => #abiCallData ( "claim" ,
#uint256 ( V0_a ) , .TypedArgs ) )
             .                          ^
[Error] Inner Parser: Parse error: unexpected token ')' following token ')'.
        Source(/home/anvacaru/rv/evm-semantics/tests/foundry/out/kompiled/foundry.k)
        Location(5104,102,5104,103)
        5104 |      rule  ( TestNumber . claim ( V0_a ) => #abiCallData ( "claim" ,
#uint256 ( V0_a ) , .TypedArgs ) )
```

**Comment by radumereuta** [comment]
Palina ran into a similar issue with a function called `Test_Foo`.
The K foundry translator needs to escape function names to avoid clashes with K keywords and make sure that any translation to sort names doesn't contain forbidden characters.

**Comment by palinatolmach** [comment]
I keep running into `kompile` issues caused by the underscore symbol in the contract name when trying to run KEVM on existing Foundry test suites (e.g., [Sablier's](https://github.com/sablier-labs/v2-core/tree/main/test)), so bumping the priority to `high`.

**Comment by iFrostizz** [comment]
We could bulk with: https://github.com/runtimeverification/evm-semantics/issues/1368

**Comment by radumereuta** [comment]
I sent this message on slack, posting it here again so we don't lose it.

There is no way to add these characters to the sort names. The K outer parser doesn't allow them.
What I was suggesting is to have a function that encodes special characters into normal alphanums. Example
`My_contract` -> `KEVMMyz5Fcontract`
Here I've chosen `z` as the special character that marks the next two characters as an ASCII encoding for underscore.
You will also have to escape `z` as well.
I find that this solution still maintains a somewhat readable representation of the original name in the generated K, which could be useful for debugging purposes.
I've also added the `KEVM` prefix, so you don't have to consider every sort you find in a definition. Only the generated ones.
I'm not sure about the input range, but you could do `zFF` and `ZFFFF` to allow for Unicode as well.

The most likely place to implement this would be here: https://github.com/runtimeverification/evm-semantics/blob/master/kevm-pyk/src/kevm_pyk/solc_to_k.py#L164
Here are some examples of how to quote/unquote such strings: https://github.com/runtimeverification/k/blob/master/kore/src/main/java/org/kframework/utils/StringUtil.java#L25

**Comment by iFrostizz** [comment]
Escaping contract name illegal characters is a good solution. We discussed a bit about it and there is actually another issue: If any contract name is duplicated across a codebase, it will silently be overwritten in the K `contracts.k` interface. We should think about if the codebases have duplicated contract names in a lot of cases, and if it wouldn't be an annoyance to have some runtime check that says "Panicking, two contracts have the same name!" in the case of libraries that couldn't play together because of this. But at the moment it may be a footgun because this is done silently.
