### ISSUE TITLE
`kevm foundry-list` not working

### ISSUE THREAD

**Issue by anvacaru** [runtimeverification/evm-semantics#1730]
1) ~~there is a key error `proofid`~~

![Image](https://user-images.githubusercontent.com/16517508/231840480-46b27073-b9ce-4cdc-a8ee-5ff4ca6c048d.png)

2) after fixing 1, it cannot read properly the values.

![Image](https://user-images.githubusercontent.com/16517508/231840592-74c2fdd8-2126-4144-8a46-409fcd5f2091.png)

**Comment by ehildenb** [comment]
Perhaps related: https://github.com/runtimeverification/pyk/pull/352

That PR includes summaries directly in the `AGProof` class, which likely means that it will fix this problem if `foundry-list-kcfg` is changed to use the `AGProof.summary` method...

**Comment by anvacaru** [comment]
I've pushed the fix for the first issue in #1702.

**Comment by anvacaru** [comment]
Fixed in #1731.
