### ISSUE TITLE
Load entire basic blocks at a time

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/evm-semantics#1742]
One of the problems of proof-reuse with KEVM is taht we have a flat byte-array representing the current program, and use a program-counter to point at an offset into that byte-array. This means that even if we do a proof about a chunk of a program that remains the same, another part of the program changing may cause that proof to become invalid. This is annoying in the CI setting, for example, where loop invariants need to mention specific chunks of the program.

One way to make this less of a problem is to load entire basic blocks of the program at a time. Essentially, we would:

- At program-load time, break the bytecode up into basic-blocks directly, and store the blocks in a map of `PROGRAM_COUNTER_BLOCK_START |-> bytecode_chunk`
- Each time we step into a basic block, we pull that entire bytecode chunk onto the `<basic-block>` cell, and execute that by consuming it from the beginning (until it is empty, then we load the next basic block).

This would enable us to write proofs about chunks of bytecode at more flexible offsets rather than having them all be fixed together. It may enable more proof-reuse.

--------

Tasks:

- [ ] Break KEVM execution into basic-blocks when loading programs (any time `<program>` cell changes). Use a new `#loadProgram` construct which:
  - Updates the `<program>` cell.
  - Loads the `<basic-blocks>` cell. As a first cut, just break the program into `JUMPDEST` labelled basic blocks.
  - Whenever we have an empty `<basic-block>` cell, load the basic-block at the current `<pc>` into this cell.
  - When we get to `#execute`, just take the first byte off `<basic-block>` cell as the next opcode, instead of reading at an offset into the `<program>`.
- [ ] Make an example looping proof with a single basic block.

Resources:

- Main execution driver: https://github.com/runtimeverification/evm-semantics/blob/master/include/kframework/evm.md#execution-macros
- Example hand-written EVM "interactive" test you can extend/use: https://github.com/runtimeverification/evm-semantics/blob/master/tests/interactive/sumTo10.evm. Example of running an "interactive" test: https://github.com/runtimeverification/evm-semantics/blob/0e7955ec833d363ad2aed1248fdcc87b84167d19/Makefile#L462
- Want to scale to target `make test-conformance -j12`.

**Comment by lucasmt** [comment]
This makes sense to me. This should also make the proofs more composable, right? For example, we can symbolically execute a function while abstracting away the rest of the bytecode.

When writing the invariant, would we then identify the basic block by the bytecode in the `<basic-block>` cell?

**Comment by PetarMax** [comment]
Yes, this is certainly one way of achieving this - this would also have to take into account how the program counter is manipulated. The proofs would have to be independent of the `PROGRAM_COUNTER_BLOCK_START` bit.

How would this interact with the jump table?

**Comment by palinatolmach** [comment]
@ehildenb do we still plan to do this?

**Comment by ehildenb** [comment]
There is an implementation of this here: https://github.com/runtimeverification/evm-semantics/pull/1805

It's unclear what the problem with that implementation is (can't remember), but I think it also may no tbe really totally feasible anyway.

We can probably close both that PR and this issue.
