### ISSUE TITLE
Migrating to KBuild

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/evm-semantics#1744]
PR: https://github.com/runtimeverification/evm-semantics/pull/1603

### Enabling changes in `kbuild`
- https://github.com/runtimeverification/pyk/issues/585
- https://github.com/runtimeverification/pyk/issues/586

### Removing `bin/kevm` bash script (moving bash code to python code)

- [ ] Migrate `run_interpret` logic to kevm-pyk: https://github.com/runtimeverification/evm-semantics/blob/master/bin/kevm#L148
- [x] pyk prover needs to have a flag `--legacy` [here](https://github.com/runtimeverification/evm-semantics/blob/master/kevm-pyk/src/kevm_pyk/__main__.py#L262) which allows calling the old `kprove` binary directly, so that we can  move all [this logic](https://github.com/runtimeverification/evm-semantics/blob/ee945dfe63e4b17626a028c9fad3e3c79c2c295a/bin/kevm#L148) into Python.
- [x] We need a way to detect directory layout in kevm-pyk, to replicate a lot of the logic about how KEVM is built on macs: https://github.com/runtimeverification/evm-semantics/blob/ee945dfe63e4b17626a028c9fad3e3c79c2c295a/bin/kevm#L67 (logic to be migrated here: https://github.com/runtimeverification/evm-semantics/blob/ee945dfe63e4b17626a028c9fad3e3c79c2c295a/kevm-pyk/src/kevm_pyk/__main__.py#L120)
- [ ] Rename `kevm-pyk` to `kevm`, ship the Python executable directly.

### Python code + Makefile for build migrates to kbuild configuration

- [ ] Hook-namespaces: https://github.com/runtimeverification/evm-semantics/blob/ee945dfe63e4b17626a028c9fad3e3c79c2c295a/kevm-pyk/src/kevm_pyk/kevm.py#L159
- [ ] Concrete-rules: https://github.com/runtimeverification/evm-semantics/blob/ee945dfe63e4b17626a028c9fad3e3c79c2c295a/kevm-pyk/src/kevm_pyk/kevm.py#L163
- [ ] md-selector: https://github.com/runtimeverification/evm-semantics/blob/ee945dfe63e4b17626a028c9fad3e3c79c2c295a/kevm-pyk/src/kevm_pyk/__main__.py#L116
- [ ] LLVM backend specifics for Mac/non-Mac: https://github.com/runtimeverification/evm-semantics/blob/ee945dfe63e4b17626a028c9fad3e3c79c2c295a/kevm-pyk/src/kevm_pyk/__main__.py#L120
- [ ] Example build of Haskell: https://github.com/runtimeverification/evm-semantics/blob/ee945dfe63e4b17626a028c9fad3e3c79c2c295a/Makefile#L231. Retain, for example, that building C library dependencies are handled by Makefile, which can be handled in KBuild preprocess hook: https://github.com/runtimeverification/evm-semantics/blob/ee945dfe63e4b17626a028c9fad3e3c79c2c295a/Makefile#L241
- [ ] A more complicated example is the `make build-node` case, which integrates the LLVM backend interpreter into an external client via the LLVM backend's "library" mode: https://github.com/runtimeverification/evm-semantics/blob/ee945dfe63e4b17626a028c9fad3e3c79c2c295a/Makefile#L273. We need to have `kbuild` handle the build up to this ponit: https://github.com/runtimeverification/evm-semantics/blob/ee945dfe63e4b17626a028c9fad3e3c79c2c295a/Makefile#L284, which adds the `--backend node` option, which triggers this line: https://github.com/runtimeverification/evm-semantics/blob/ee945dfe63e4b17626a028c9fad3e3c79c2c295a/bin/kevm#L76, which builds the LLVM backend kore definition, dynamic library, and dt files. Then this takes over: https://github.com/runtimeverification/evm-semantics/blob/ee945dfe63e4b17626a028c9fad3e3c79c2c295a/Makefile#L291 to build the final application. So kbuild should handle everything up to the kore file, dynamic lib, and dt file generation, then use a postprocess hook to call into the cmake build system.

**Comment by palinatolmach** [comment]
@ehildenb @tothtamas28 can I check with you on the status of this task? Should we close or move it to backlog? Thanks!

**Comment by tothtamas28** [comment]
This is a medium- to long-term goal, can be moved to backlog I think.
