### ISSUE TITLE
Generating addrFromPrivateKey lemmas for missing ecdsaPubKey hook

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/evm-semantics#1765]
Because of ECDSAPubKey not being implemented on concrete inputs for the Haskell backend, we cannot rely on it being present when writing Foundry property tests (see: https://github.com/runtimeverification/haskell-backend/issues/3573).

But it's not uncommon to supply a random private key in a property test, then use `vm.addr(...)` cheatcode to turn said private key into an ethereum address that can be used. This pattern is especially used with contracts where signatures are checked onchain.

To get around this https://github.com/runtimeverification/evm-semantics/pull/1766 allows us to write lemmas directly for the addresses needed in the tests. Given a private key `KEY` (encoded in hex, for example: `0x2b8ba85ff7f2c7fa62cddb20ae40ef2553b9fdbff086f60d1647ecaab15af867`), and the associated Etherem address `ADDR` (encoded as a decimal integer, for example: `1204788665628904891128108629487072145087352593841`), you can add the following K lemma to your `lemmas.k` for a project to help the Haskell backend reason about that case:

```
rule #addrFromPrivateKey(KEY) => ADDR [priority(40)]
```

So, given `KEY`, how do you figure out the correct `ADDR`?

First, install `ganache-cli`:

```
npm install -g ganache-cli
```

Then run, in one terminal, `ganache-cli`:

```
ganache-cli
```

Wait for it to start up, then in a file called `ganache.in`, put the following contents:

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "personal_importRawKey",
  "params": ["KEY", "0x"]
}
```

Then, in another terminal, run the following command to send this request to ganache-cli:

```
curl -s -X POST 'http://127.0.0.1:8545' --data @ganache.in -H "Content-Type: application/json"
```

It will output a response that looks like this:

```
{"id":1,"jsonrpc":"2.0","result":"HEX_ADDR"}
```

Take the `HEX_ADDR`, and put it in this website to convert it to decimal: https://www.rapidtables.com/convert/number/hex-to-decimal.html, which gives you `ADDR`, so that you can make your lemma!

**Comment by palinatolmach** [comment]
Merged this issue with the one that describes the missing `ECDSA hook` problem https://github.com/runtimeverification/haskell-backend/issues/3573.

**Comment by palinatolmach** [comment]
Merged this issue with the one that describes the missing ECDSA hook problem https://github.com/runtimeverification/haskell-backend/issues/3573.
