### ISSUE TITLE
Factor out `Foundry.proof` method for extracting the reachability proof of a given method

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/evm-semantics#1769]
As https://github.com/runtimeverification/evm-semantics/pull/1755#discussion_r1174983732 states, we should:

- Add a method `Foundry.proof(...)`, which returns the `APRProof` of a given method.
- Set it up to automatically run the `setUp` method if needed.
- Set it up to automatically detect if rekompilation is needed.

**Comment by nwatson22** [comment]
Currently waiting for #1798, as that already has code in it to detect if rekompilation is needed.
