### ISSUE TITLE
Re-arrange gas definitions

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/evm-semantics#1789]
Currently we have all teh functions regarding gas usage defined in `evm.md` directly. Following https://github.com/runtimeverification/evm-semantics/pull/1726, we have a dedicated `gas.md` file, which we could consolidate gas definitions into. I think a good structure would be:

- Module `GAS-SYNTAX` which defines the gas arithmetic operators and the lifting of `Int` operators into `Gas` operators.
- Module `GAS-INFINITY` which defines `#gas(...)` as the point in a pointed set.
- Module `GAS-FEES` which defines all the schedule constants and gas functions (like `Cgascap(...)` etc...)
- Module `GAS-SIMPLIFICATION` which defines all the `simplification` rules related to gas and infinite gas (marked as `symbolic` so that only the Haskell backend gets it).
- Module `GAS` which imports all the above modules.

**Comment by dkcumming** [comment]
Oh whoops, I had this tab open from last night and was thinking to start on this if the HydraDX audit commit wasn't in yet. I didn't refresh the page and didn't see Scott was assigned
