### ISSUE TITLE
Improve the output of the KEVM Visualizer

### ISSUE THREAD

**Issue by anvacaru** [runtimeverification/evm-semantics#1792]

**Comment by anvacaru** [comment]
In foundry.md there are a few subconfigurations only used by specific cheat codes such as expectRevert, expectEmit or prank. Setting those cells as `optional` perhaps could improve performance for the tests that do not use these cheat codes.

**Comment by ehildenb** [comment]
If we want to omit some cells in the output (and improve the output), I think a better way is:

- In the `KEVM` class (https://github.com/runtimeverification/evm-semantics/blob/c6fb207374940b2b12f509d58a1451d76768cf0b/kevm-pyk/src/kevm_pyk/kevm.py#LL32C12-L32C24), we have it inheriting from `KRun` and `KProve`, which implements `pretty_print`. We can override `pretty_print` in KEVM to first walk the AST and do:
  - Print large numbers as hex strings.
  - Print bytes as hex strings.
  - Omit uninteresting components of the configuration.
- Then have `pretty_print` just call `super().pretty_print(...)`

**Comment by anvacaru** [comment]
Additional ideas to improve the output:
   - replace the calldata selector bytes with the function signature fetched from ABI?
   - assign aliases to each node id to improve readability.

**Comment by palinatolmach** [comment]
@anvacaru do you think any of these items are actionable?

**Comment by anvacaru** [comment]
@palinatolmach Some of them are already implemented, like `assign aliases to each node id`. 

I had an open PR for changing the bytecode and large numbers to hex(linked above). I closed it because it became stale, but I can reopen it and get it merged.

**Comment by ehildenb** [comment]
I haven't seen other requests for this yet, so closing for now.

**Comment by palinatolmach** [comment]
Reopening in view of https://github.com/runtimeverification/kontrol/issues/473.
