### ISSUE TITLE
Unsuported evm base sort type: int128

### ISSUE THREAD

**Issue by anvacaru** [runtimeverification/evm-semantics#1871]
`@lowprivuser` presented this issue on our discord server. When calling `foundry-kompile` on a contract that's using `int128`, `solc_to_k` will raise a `ValueError: Unsupported evm base sort type: int128`.

I replicated the issue with this minimal example 
```solidity

// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

contract Counter {
   int128 public number;

   function setNumber(int128 newNumber) public {
       number = newNumber;
   }
}
```

**Comment by fasapa** [comment]
@anvacaru (u)int24 too. Got the same error: `ValueError: Unsupported evm base sort type: int24`
