### ISSUE TITLE
Makefile papercuts

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/evm-semantics#1887]
There are a few papercuts in the Makefile setup for KEVM, as identified by @tothtamas28:
* `make plugin-deps` is necessary after `make clean`
* `make deps` doesn't make `deps-plugin`
* `make distclean` doesn't call `make clean` in `deps/plugin` or `mvn clean` in `deps/k`

**Comment by anvacaru** [comment]
@tothtamas28 can we close this issue?

**Comment by tothtamas28** [comment]
Yes, these targets are no longer present in the `Makefile`.
