### ISSUE TITLE
Improve pretty printing of terms

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/evm-semantics#1896]
A simple way to improve the readability of output would be to insert whitespace around parentheses in a smarter way.
```
//before
 rule  ( AccountParamsTest . testDealSymbolic ( V0_value : uint256 ) => #abiCallData ( "testDealSymbolic" , #uint256 ( V0_value ) , .TypedArgs ) )
// after
 rule  (AccountParamsTest . testDealSymbolic(V0_value : uint256) => #abiCallData("testDealSymbolic", #uint256(V0_value), .TypedArgs))
```
Characters to consider: `( ) [ ] ,`

Not inserting whitespace around parentheses is not going to cause reparsing problems, and I think it improves readability of the code significantly. I've done something similar for the IDE integration: https://github.com/runtimeverification/k/pull/3331

This is something we discussed at the ERCse-circe meeting as a low-priority, but low-hanging fruit.

**Comment by ehildenb** [comment]
Well sure, but no one is reading the `foundry.k` in terms of using the tool itself I don't think? It's mostly juts for the kompiler.

**Comment by ehildenb** [comment]
No, the `format` attributes are ignored, it's the simplest and easiest unparser possible: https://github.com/runtimeverification/pyk/blob/54946116190eb2af7a4b5de58fbc2279b64260da/src/pyk/kast/pretty.py#L376

**Comment by anvacaru** [comment]
`foundry.k` and `contracts.k` are intermediate files. I don't think we should make a priority out of formatting them. I'm closing this.
