### ISSUE TITLE
Cheatcodes for creating fresh symbolic values

### ISSUE THREAD

**Issue by lucasmt** [runtimeverification/evm-semantics#1905]
It would be good to have cheatcodes that can generate a symbolic value of a given type, for example:
- `freshBytes32()`
- `freshUInt256()`
- `freshBool()`
- `freshAddress()`

In the current engagement we are simulating these by using the `symbolicStorage` cheatcode:
```
contract UInt256Wrap {
    uint256 public value;
}

contract KevmUtil is KEVMCheats {
    function freshUInt256() internal returns (uint256) {
        UInt256Wrap x = new UInt256Wrap();
        kevm.symbolicStorage(address(x));
        return x.value();
    }
}
```
But this creates an overhead since it requires deploying a contract every time.

**Comment by ehildenb** [comment]
How about `freshUInt(uint8)`, so that we can generate fresh uints in any range? Can also do `freshSInt(uint8)` too.
