### ISSUE TITLE
KEVM gets stuck on `#assume(false)`

### ISSUE THREAD

**Issue by lucasmt** [runtimeverification/evm-semantics#1944]
KEVM seems to get stuck when it hits an `#assume(false)`. For example, the following minimal example fails because it branches inside the `atLeastOneIsValidAddress` function, with two of the branches evaluating to `#assume(true)` and the last one evaluating to `#assume(false)`. The `#assume(false)` branch then gets stuck.
```
    function atLeastOneIsValidAddress(address alice, address bob)
        internal
        returns (bool)
    {
        if (alice != address(0)) {
            return true;
        } else if (bob != address(0)) {
            return true;
        } else {
            return false;
        }
    }

    function test_assume_return(address alice, address bob) public {
        vm.assume(atLeastOneIsValidAddress(alice, bob));

        assert(true);
    }
```
In a situation like this, we would want `#assume(false)` to add `#Bottom` to the constraints, which would cause the branch where it happens to be vacuously satisfied. This would be consistent with the behavior in Foundry, which ignores inputs for which the `assume` evaluates to `false`.

`#assume` is implemented as `rule <k> #assume(B) => . ... </k> ensures B` in `foundry.md`, but KEVM gets stuck on `#assume(false)`, so is this a restriction on the `ensures` clause? Is `ensures false` not allowed? If this is the case, is there a way to implement an alternative `rule` for `#assume(false)` that will have the behavior that we need (discarding the vacuous branch)?

On the other hand, as @ehildenb pointed out, this can cause issues where a proof might vacuously pass because the user accidentally added contradictory assumptions:

> But you could also have something like `vm.assume(pred1); vm.assume(pred2);` (separated by a large chunk of code, even) and as a user you don't realize that `pred1 /\ pred2 == false`, so it vacuously discards that branch and leads to the proof passing, even though it didn't actually prove anything.

To prevent this from happening accidentally, we might want to do one of the following:

- Create a separate cheatcode, like `vm.assume_allow_vacuous`, that allows this behavior, so that the user needs to explicitly say when they want to accept vacuous branches.
- Another option is to mark branches that passed because they are vacuous and report that to the user. This way the user will know if a branch became vacuous accidentally.

**Comment by anvacaru** [comment]
I created a minimal definition outside of evm-semantics and looks like `kprove` and `kore-exec` can apply the `foundry-assume(false)` rule and simplify to `#Bottom`, unlike the example above where the `kore-rpc` will remain stuck.

Minimal definition with claim example: https://gist.github.com/anvacaru/7a47b6f3c48a73008c17d500bac7afbc

To run with debug logging(kudos to @goodlyrottenapple for this):
```
KORE_EXEC_OPTS='--log-level debug' kprove claims.md &> run.log
```
And the `run.log` file: [run.log](https://github.com/runtimeverification/evm-semantics/files/12259041/run.log)

**Comment by anvacaru** [comment]
Fixed in: https://github.com/runtimeverification/pyk/pull/587
