### ISSUE TITLE
`#setPrank` deletes `ACCTTO`

### ISSUE THREAD

**Issue by iFrostizz** [runtimeverification/evm-semantics#1945]
This is blocking https://github.com/runtimeverification/evm-semantics/pull/1862 for filtering calls to test / cheatcode address
When reading from the cut rules after a prank, the address that should have been at the position of the `ACCTTO` parameter in multiple rules such as `#call`, `#callWithCode`, `#mkCall` is 0.
It can be reproduced by writing a test such as:

```solidity
function test_prank(address who) public {
    kevm.infiniteGas();
    vm.assume(who != 0xfcC345e00009B3E5dF2FCAFbe77B1Fd66e736a68);
    vm.prank(who);
    test_contract.call(abi.encodeWithSignature("func()"));
}
```

While looking into the kcfg viewer, we can see that for any `CALL` before the prank, the `ACCTTO` is correct

![image](https://github.com/runtimeverification/evm-semantics/assets/51274081/c104d7e6-a6df-4fb2-ac20-96b76dadf3fa)
*call to vm.assume(who != ...)*

![image](https://github.com/runtimeverification/evm-semantics/assets/51274081/0aee3622-07c8-402d-a86e-97d9e2b282ea)
*call to vm.prank(who)*

After the call to prank, it's always 0.

![image](https://github.com/runtimeverification/evm-semantics/assets/51274081/7b0339cd-1c2c-4217-b6e2-f724e3668f4b)
![image](https://github.com/runtimeverification/evm-semantics/assets/51274081/96ffb0dd-98ad-409b-a684-3bb1956e018f)
![image](https://github.com/runtimeverification/evm-semantics/assets/51274081/7c0cd1d1-f2ad-42be-9884-ccb592135d72)
![image](https://github.com/runtimeverification/evm-semantics/assets/51274081/82b13f0b-9b50-4bb1-9313-02724360c159)

**Comment by anvacaru** [comment]
@iFrostizz, this behavior seems similar to the one presented in https://github.com/runtimeverification/evm-semantics/issues/1951. 

I was not aware that we do not execute initializer code, meaning that values outside of the `setUp` function would be uninitialized. This would explain why you see the 0 address.

 Can you try replicating the test with a call to an address initialized in the `setUp` function or to a hardcoded address?

**Comment by iFrostizz** [comment]
Agree, thanks for figuring this out @anvacaru . I ran the proof by writing the address on the stack in the test directly so that it wouldn't be assigned while executing the init code and the `to` is not zero anymore.

**Comment by anvacaru** [comment]
All right, I'm closing this in favor of #1951.
