### ISSUE TITLE
 Running `kevm foundry-prove --bug-report` writes to the same bug report for all proofs

### ISSUE THREAD

**Issue by geo2a** [runtimeverification/evm-semantics#1966]
Running a KEVM Foundry on more than one test, i.e. `kevm foundry-prove --test TEST1 --test TEST2 --bug-report` will re-use the same bug report archive. While no information is lost, the innards of the archive are difficult to map to the individual proofs.

I suggest we disambiguate the bug reports, i.e. for every `--test TESTX` we generate a separate bug report which is name `TESTX_bug_report.tar`.

**Comment by iFrostizz** [comment]
Should be an quick fix, we could factor the `BugReport` creation in a function that takes in the `test_id` if `bug_report` is not `None`. This will let us factor in the `bug_report` name in one place if it has to ever change. Blocked by https://github.com/runtimeverification/evm-semantics/pull/2026

**Comment by iFrostizz** [comment]
TODO
https://github.com/runtimeverification/evm-semantics/blob/ba06470f78f9b37ff9058b62a87c749a5c7aee13/kevm-pyk/src/kontrol/foundry.py#L537
https://github.com/runtimeverification/evm-semantics/blob/ba06470f78f9b37ff9058b62a87c749a5c7aee13/kevm-pyk/src/kontrol/foundry.py#L802
https://github.com/runtimeverification/evm-semantics/blob/ba06470f78f9b37ff9058b62a87c749a5c7aee13/kevm-pyk/src/kontrol/foundry.py#L840
https://github.com/runtimeverification/evm-semantics/blob/ba06470f78f9b37ff9058b62a87c749a5c7aee13/kevm-pyk/src/kontrol/foundry.py#L885
https://github.com/runtimeverification/evm-semantics/blob/ba06470f78f9b37ff9058b62a87c749a5c7aee13/kevm-pyk/src/kontrol/foundry.py#L914

**Comment by palinatolmach** [comment]
Was this issue closed by https://github.com/runtimeverification/evm-semantics/pull/2125?

**Comment by geo2a** [comment]
I think so! Closing now, thanks.
