### ISSUE TITLE
Investigate consistency of account id/caller id in a direct call to function

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/evm-semantics#1972]
When making a direct call to a contract method (not a test method), we should investigate:

- Which accounts are present?
- What are the values of `<id>`, `<caller>`, and `<origin>`.
- Which account are we executing as?

In general, these should all be symbolic, but the account we're executing as should not be the hardcoded foundry one, but an arbitrary one, for generality of the generated KCFG.

**Comment by yale-vinson** [comment]
@palinatolmach This one is very stale. Is it worth keeping, or should we close it?

**Comment by anvacaru** [comment]
Jumping in because I saw the notification. I think this issue can be closed since these items have already been addressed in the first iteration of CSE.

**Comment by yale-vinson** [comment]
OK, sounds good to me. I thought it might be addressed with work done in the last 6 months, and happy to get it off the board. Thank you, @anvacaru!
