### ISSUE TITLE
Enable Foundry tests on Nix CI

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/evm-semantics#1980]
We should enable Foundry tests on Nix on CI, see https://github.com/runtimeverification/evm-semantics/pull/1977/files#r1276950257

This could be done by:

- Updating all our contracts in the test-suite to use `solc` 0.8.19 in their pragmas, or
- Change our `flake.nix` to pin version 0.8.13 of `solc` (perhaps here: https://github.com/runtimeverification/evm-semantics/blob/8960441a7bf0b9961833a47ad72826cd17792f19/nix/solc/default.nix#L48)

**Comment by palinatolmach** [comment]
@ehildenb we're now running one Foundry smoke test ([`AssertTest.test_assert_true`](https://github.com/runtimeverification/kontrol/blob/b50f4844ccfd5a54e964b821e4ba2100077411fb/package/test-project/test/Simple.t.sol)) on Nix on CI (https://github.com/runtimeverification/kontrol/pull/146). Shall we consider this issue closed, or do you think we should run more tests from our Foundry test suite?

**Comment by anvacaru** [comment]
I'll close this for now since we are executing a foundry test on Nix on CI.
