### ISSUE TITLE
#newAccount and #accountNonexistent checking very similar things

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/evm-semantics#199]
Currently these two functions are checking for similar things, and perhaps we could do a small refactor to make them re-use some of the same code-paths.

Problems are:

1.  They can't be quite exactly the same because `#newAccount` is used to create an account, and it's OK to first send funds to an account (making it existent), then create the account later (so `#newAccount` should not error out).
2.  More technical issue, the OCaml glue code which makes KEVM able to act as a VM inside the Mantis client relies of klabel `accountEmpty` (with function `#accountEmpty`) existing and having its current signature.

**Comment by anvacaru** [comment]
Closing this. `#accountNonExistent` has been refactored to use `#accountEmpty`.
