### ISSUE TITLE
Clarify and Improve `--test` Parameter Functionality in `kevm foundry-prove`

### ISSUE THREAD

**Issue by RaoulSchaffranek** [runtimeverification/evm-semantics#2063]
I've encountered issues with the `--test` parameter when executing specific functions, such as `transfer`, using the `kevm foundry-prove` command on an ERC20 contract. The current implementation is ambiguous, making it challenging to precisely specify the function to be tested.

Besides, it's unclear what the expected format for the `--test` parameter is. Should it be a Python regular expression, a list of Python regexes, or a verbatim string?

**Reproduction Steps**:

1. Executing `transfer` function with a short name:

   ```bash
   > kevm foundry-prove --test CirceToken.transfer
   ...
   ValueError: Found ['CirceToken.transfer(address,uint256)', 'CirceToken.transferFrom(address,address,uint256)'] matching tests, must specify one
   ```

2. Executing `transfer` function with a full signature:

   ```bash
   > kevm foundry-prove --test 'CirceToken.transfer(address,uint256)'
   ...
   ValueError: Proof with id `CirceToken.transfer(address,uint256):uint256)` is not up to date.
   ```

**Comment by yale-vinson** [comment]
@tothtamas28 can you answer Raoul's questions above? Is there something that we can do to improve this from your perspective?

**Comment by tothtamas28** [comment]
I checked the code ([here](https://github.com/runtimeverification/evm-semantics/blob/85d786ecfbf79219755a5c61598a8e5b43df29e7/kevm-pyk/src/kontrolx/foundry.py#L269C9-L269C23)), and it looks like it performs regex-based filtering on tests (in format `f'{contract.name}.{method.signature}'`).

I agree this should be documented, and perhaps made more reasonable: it doesn't make too much sense to give the user the flexibility and complexity of regexes if in the end the match is required to be unique.

> Executing transfer function with a full signature

There's no confusion here: a single test is matched based on the full signature, but the definition is not up-to-date, hence rekompilation is necessary.
