### ISSUE TITLE
`setUp()` function proof not reinitializing when the tests change

### ISSUE THREAD

**Issue by nwatson22** [runtimeverification/evm-semantics#2073]
Currently, when we change a foundry test in a contract that has a `setUp` function, the setUp function itself will not necessarily update. (This seems to happen regardless of whether or not we add `--reinit`). In the case where we don't add `--reinit`, this is fine, but it causes a problem when the new proof is generated using the old `setUp` function. The proof will fail erroneously because the `code` cell is used from the (outdated) `setUp` proof, so will fail to match the code cell for the target node, which uses the updated version of the code.

The problem with `--reinit` not reinitializing the `setUp` proof should be solved by #2064 and the code cell matching issue by #2020, but I am creating this issue as a note/reminder.

**Comment by ehildenb** [comment]
We should not be copying the `code` cell from the output of the `setUp` function, just the `storage`, `origStorage`, `balance`, and `nonce`. That way, it won't break in this way.

**Comment by nwatson22** [comment]
> We should not be copying the `code` cell from the output of the `setUp` function, just the `storage`, `origStorage`, `balance`, and `nonce`. That way, it won't break in this way. Requires modification here:
> 
> https://github.com/runtimeverification/evm-semantics/blob/75583c11ece56073bb15efdb7daa4cf6cec5901d/kevm-pyk/src/kontrol/foundry.py#L1338

@ehildenb Are you sure that is the preferable behavior (just copying storage, origStorage, balance, and nonce? I am thinking about the case where `setUp()` creates a contract. In that case wouldn't we want the account for that contract to be copied with its code?

 I tried to address the issue in #2064 now by, after copying the accounts cell, overwriting the code cell for the account `Foundry.address_TEST_CONTRACT()` to make sure it gets the newer version of the code.

**Comment by ehildenb** [comment]
Yeah, if the setup function creates another contract, that should be copied as well. But the code from the test contract shouldn't be included I think, because that code can change even if the setup or storage doesn't.
