### ISSUE TITLE
Outdated K causes incorrect KEVM/Kontrol output 

### ISSUE THREAD

**Issue by palinatolmach** [runtimeverification/evm-semantics#2097]
When building from source, it seems that KEVM doesn't throw an error if an older version of K is being used, which leads to incorrect or outdated results produced by KEVM and Kontrol. Both me and @nwatson22 seem to have had this issue, which was fixed by running `kup install k.openssl.procps --version v$(cat deps/k_release)`. Perhaps, we could warn the user about the outdated K version being used, or update it automatically?

**Comment by palinatolmach** [comment]
@ehildenb @tothtamas28 can I ask for your opinion on this? We have `deps/k_release` both in Kontrol and KEVM, but I'm not sure if the version set there is or can be used outside of CI.

**Comment by tothtamas28** [comment]
> We have deps/k_release both in Kontrol and KEVM, but I'm not sure if the version set there is or can be used outside of CI.

This is primarily for CI. It comes from `pyk.K_VERSION`, which is the K version a given `pyk` version is tested against.

> Perhaps, we could warn the user about the outdated K version being used, or update it automatically?

Emitting a warning is definitely doable, you just need to compare

```python3
KVersion.parse(f'v{pyk.K_VERSION}')  # expected version
```

and

```python3
k_version()  # actual version
```

(All relevant classes and functions are defined in `pyk.kbuild.utils`.)
