### ISSUE TITLE
Remove `kontrolx`

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/evm-semantics#2113]
Remove `kevm-pyk/src/kontrolx` and corresponding CI and test code (including `tests/foundry`).

Do not remove `kevm-pyk/src/kevm_pyk/kproj/evm-semantics/foundry.md` (addressed in https://github.com/runtimeverification/kontrol/issues/61).

**Comment by yale-vinson** [comment]
@ehildenb Is this something you are actively working on or should I move it to the backlog?
