### ISSUE TITLE
Remove rule label `FOUNDRY.foundry.call` from `kevm_prove`

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/evm-semantics#2120]
First refactor `kevm_prove` so that `foundry_prove` can inject `FOUNDRY.foundry.call`  when calling the function.

1. Extract a function that creates the list of labels from the flags.
2. Pass the rule configuration directly. 

Then drop the rule label from the factory function.

After addressing the issue, the `kontrol` team should be notified so that the corresponding changes can be made in `foundry_prove`.

**Comment by anvacaru** [comment]
Attaching this to the PR https://github.com/runtimeverification/kontrol/pull/161
