### ISSUE TITLE
Update documentation to reflect the latest version of Kontrol

### ISSUE THREAD

**Issue by RaoulSchaffranek** [runtimeverification/evm-semantics#2133]
This document does not reflect the latest version of KEVM/Kontrol:

https://github.com/runtimeverification/evm-semantics/blob/master/kevm-pyk/src/kevm_pyk/kproj/evm-semantics/foundry.md

In particular, `kevm foundry-prove` is now `kontrol prove`, etc. etc.
This was reported by a user on our k-public channel.

**Comment by anvacaru** [comment]
This was addressed in https://github.com/runtimeverification/kontrol/pull/154.
