### ISSUE TITLE
`#parseHexBytes` should be declared total

### ISSUE THREAD

**Issue by goodlyrottenapple** [runtimeverification/evm-semantics#2199]
Given the definitions below:
https://github.com/runtimeverification/evm-semantics/blob/42ce78b160754203f642462fcc27c09b88e8722c/kevm-pyk/src/kevm_pyk/kproj/evm-semantics/serialization.md?plain=1#L183-L195

`#parseHexBytes` could be declared total, because the ceil of `#parseHexBytesAux(S)` is `lengthString(S) >=Int 2 or S == ""` so we only have to check that `forall S. lengthString( #alignHexString(S) ) >=Int 2 or #alignHexString(S) == ""` to conclude that `#parseHexBytes` is total:

* if `lengthString(S) modInt 2 ==Int 0` then we have to show `lengthString( S ) >=Int 2 or #alignHexString(S) == ""` which is obvious because the string can only be of length 0, 2, 4, 6 ... 

* if `lengthString(S) modInt 2 =/=Int 0`  then we have to show `lengthString( "0" +String S ) >=Int 2 or "0" +String S == ""`, but we also know that `lengthString( S ) > 0` (since it can only be of length 1, 3, 5, ...), and from  `lengthString( "0" +String S ) >=Int 2` we conclude `1 + lengthString( S ) >=Int 2`, `lengthString( S ) >=Int 1`, `lengthString( S ) >Int 0`

**Comment by ehildenb** [comment]
`#parseHexBytes("zzzz")` is not defined I don't think.

**Comment by goodlyrottenapple** [comment]
Ah I see. So string2base isn't total?

**Comment by ehildenb** [comment]
Probably something we could do is avoid using `#parseHexBytes` altogether by using a different data representation where it's used. Or defining our own custom hex sting format regex, and then make it total.

**Comment by ehildenb** [comment]
How often is this an issue for the booster reasoning?
