### ISSUE TITLE
Opt in to new type inference method

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/evm-semantics#2213]
@Scott-Guest has implemented a new type inference algorithm that does not rely on Z3; using it should reduce CI flakiness during parsing by not requiring a lot of files to be opened and processes to be spawned.

At the moment, the new mode is opt-in and can be enabled by passing:
```
--type-inference-mode simplesub
```
as a flag to `kompile`.

**Comment by radumereuta** [comment]
After this https://github.com/runtimeverification/k/pull/3855 is merged, you should be able to add it to `kprove` as well.

**Comment by Scott-Guest** [comment]
Closed by #2421
