### ISSUE TITLE
Duplicate lemmas between two different files

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/evm-semantics#2250]
_Originally posted by @ehildenb in https://github.com/runtimeverification/evm-semantics/pull/2247#discussion_r1447681130_

It appears we may have duplication of some lemmas in KEVM, which could be a source of slowdown.

**Comment by jberthold** [comment]
I can try to remove the entire module (and related imports and test files + references).
Was going to add that to #2247 but maybe better to keep it separate.

**Comment by jberthold** [comment]
According to https://github.com/runtimeverification/evm-semantics/pull/2255#issuecomment-1889677866 , the better way to de-duplicate the lemmas is to remove them from `int-simplifications.k` (thereby decoupling this module from `evm-semantics`).
