### ISSUE TITLE
Tests missing from Pytest harness

### ISSUE THREAD

**Issue by anvacaru** [runtimeverification/evm-semantics#2275]
In that case, please open an issue for porting these tests to Python.

_Originally posted by @tothtamas28 in https://github.com/runtimeverification/evm-semantics/pull/2273#discussion_r1466261154

The tests `tests/specs/benchmarks/structarg00-spec.k` and `structarg01-spec.k` are not part of the Pytest harness and are executed in `package/test-package.sh`

**Comment by ehildenb** [comment]
I don't think this is actually an issue. `test-package.sh` is used for testing the actual CLI invocations in the packages we produce. These tests are being run by the pytest harness as well.
