### ISSUE TITLE
Eliminate `klabel(_)` and `symbol` attributes

### ISSUE THREAD

**Issue by anvacaru** [runtimeverification/evm-semantics#2462]
The two attributes `klabel(_)` and `symbol` will eventually be deprecated. The K code should be updated to use the `symbol(_)` attribute instead.

**Comment by tothtamas28** [comment]
Here's a simple script that lets you list the productions in question.

```python3
from pyk.kast.att import Atts
from pyk.kast.outer import read_kast_definition
from pyk.kdist import kdist


definition_dir = kdist.get('evm-semantics.llvm')
definition = read_kast_definition(definition_dir / 'compiled.json')

for symbol, production in definition.symbols.items():
    att = production.att
    if all(key in att for key in [Atts.KLABEL, Atts.SYMBOL]):
        print(symbol, att[Atts.SOURCE], att[Atts.LOCATION])
```

You might need to adjust it a bit to find all productions, e.g. change the `kdist` target to `evm-semantics.haskell`, filter for different attributes, etc.
