### ISSUE TITLE
Bug: parsing ambiguity of KList, _,__EVM-DATA, typedArgs, eventArgs

### ISSUE THREAD

**Issue by mhhf** [runtimeverification/evm-semantics#286]
I'm struggling parsing a kast expression in prefix form, in particular the following one:
```
<gas> VGas => `#if_#then_#else_#fi_K-EQUAL` ( `notBool_` ( `_==K_` ( ABI_x, #token("0", "Int") ) ), `_-Int__INT` ( VGas, #token("20491", "Int") ), `_-Int__INT` ( VGas, #token("5491", "Int") ) ) </gas>
```

Parsing it yields an ambiguity (full error [here](https://gist.githubusercontent.com/mhhf/dd371105a1cd10559d0e24c8906f46b8/raw/3873ca57a7a84cc66616229491a2081e89d30ce2/gistfile1.txt)):
```
[Warning] Inner Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: syntax KList ::= KList "," KList
...
2: syntax KList ::= KList "," KList
```

It is because KList, _,__EVM-DATA, typedArgs, eventArgs have all the same delimiters `,`. 
A solution would either redefine KList delimiter as `,,` or redefine the evm-semantics List delimiter to be different from `,`.

**Comment by ehildenb** [comment]
@dwightguth they are trying to auto-generate the specification from a higher-level DSL. As writing an unparser is probably beyond the scope of what they want to do, using KAST is the next best thing.

**Comment by dwightguth** [comment]
Hmmm. We could make K's unparser be available on the command line... Or we could change the list terminators in the evm semantics like they suggested.  We might also be able to just tag them with the avoid attribute. Changing the syntax of K is probably out though. Too much depends on this being as it is now.

**Comment by mhhf** [comment]
to give you context: we have a json output containing a gas cell and need some way to unparse it to put it back in a `.k` spec.
the main problem for me to develop a unparser is to find a consistent way to infix/mixfix KApply nodes, since its not directly derivable from the "label" information.
e.g. compare `_-Int__INT` `#if_#then_#else_#fi_K-EQUAL` `notBool_` `_==K_`
some of them have a suffix (e.g. `_INT`, `K-EQUAL`) and some of them don't, also its not clear what is considered a suffix. If somehow the json notation could use labels not containing suffixes for the unparsing I could inline the KAplly arguments for `_`, assuming the number of `_` always matches the argument length.
another workaround would be a command line utility which exposes the unparsing from the k side: `kunparse <path/to/json> <path/to/term.kast>`
