### ISSUE TITLE
KEVM  Semantics RETURNDATACOPY CALLDATACOPY CREATE

### ISSUE THREAD

**Issue by antonper** [runtimeverification/evm-semantics#745]
Hello,
I looked into the Semantics of KEVM and have few questions that I would like to clarify. They look like a small derivations of KEVM from EVM yellowpaper specification. I suspect that that can be done for the sake of verification.

```
    syntax TernStackOp ::= "CALLDATACOPY"
 // -------------------------------------
    rule <k> CALLDATACOPY MEMSTART DATASTART DATAWIDTH => . ... </k>
         <localMem> LM => LM [ MEMSTART := CD [ DATASTART .. DATAWIDTH ] ] </localMem>
         <callData> CD </callData>
```

```
    syntax TernStackOp ::= "RETURNDATACOPY"
 // ----------------------------------------
    rule <k> RETURNDATACOPY MEMSTART DATASTART DATAWIDTH => . ... </k>
         <localMem> LM => LM [ MEMSTART := RD [ DATASTART .. DATAWIDTH ] ] </localMem>
         <output> RD </output>
      requires DATASTART +Int DATAWIDTH <=Int #sizeByteArray(RD)

    rule <k> RETURNDATACOPY MEMSTART DATASTART DATAWIDTH => #end EVMC_INVALID_MEMORY_ACCESS ... </k>
         <output> RD </output>
      requires DATASTART +Int DATAWIDTH >Int #sizeByteArray(RD)
```
The RETURNDATACOPY throws EVMC_INVALID_MEMORY_ACCESS if size of `RD` is smaller then expected. Yellowpaper in that case pushed 0s.
![image](https://user-images.githubusercontent.com/7038613/76087792-26a19900-5fb7-11ea-9381-b0df1a6b52d0.png)
CALLDATACOPY has similar behavior. 
![image](https://user-images.githubusercontent.com/7038613/76088025-9c0d6980-5fb7-11ea-85e6-2af956bfd9f8.png)
Why does EVMC_INVALID_MEMORY_ACCESS for the copy out of bounds of `CD` is not thrown in that case. Does `CD [ DATASTART .. DATAWIDTH ]`  takes into the account the 0s if it is out of bounds of CD sequence?

Last question is regarding the CREATE.  Execution initialization code usually ends, up with `RETURN` op. But the yellowpaper CREATE opcode defines explicitly that the output data should be wiped. I have not seen in KEVM `#finishCodeDeposit` that the `<output>` cell of the creator program was erased. Is it erased? I am new to KEVM semantics and could have just misunderstood something.
Thanks for help!

**Comment by daejunpark** [comment]
@ehildenb you may want to look into this as people currently discussing on what's standard behavior against out-of-range codecopy in the telegram security channel.

**Comment by daejunpark** [comment]
@antonper @0age A bit of clarification regarding out-of-range code/data copy semantics here.

For the code/data copy opcodes:
- CODECOPY
- EXTCODECOPY
- CALLDATALOAD
- CALLDATACOPY
- RETURNDATACOPY

All the major EVM implementations (geth, erigon, nethermind, besu, py-evm, and ethereumjs) agree on the behavior of those opcodes.  That is, out-of-range access silently pads zero except RETURNDATACOPY (which reverts).

These behaviors are consistent with KEVM since the semantics of the byte read operator "`DATA [ START .. WIDTH ]`" pads right to zero for out-of-range access, where it has the additional conditional rule for RETURNDATACOPY as @antonper mentioned.

This is also consistent with Yellow Paper!
- For CODECOPY and EXTCODECOPY, Yellow Paper specifies that it should pad with `STOP` for out-of-range access, where the value of the `STOP` opcode is `0x0`, thus it essentially pads with zero.  (Note that it doesn't mean executing the STOP opcode, but just write the STOP opcode to the memory.)
- For RETURNDATACOPY, Yellow Paper is a bit confusing, but Section 9.4.2. "Exceptional Halting" defines the halting condition `Z` which includes the out-of-range RETURNDATACOPY, i.e., `w = RETURNDATACOPY /\ \mu_s[1] + \mu_s[2] > ||\mu_o||` (https://github.com/ethereum/yellowpaper/blob/30782852fef61f61a247dafbdad814ae7e00fb39/Paper.tex#L1130)

So, at least for the out-of-range code/data copy behavior, all the implementations, KEVM, and Yellow Paper agree, which is great!

**Comment by daejunpark** [comment]
For reference:

Go Ethereum (geth):
- CODECOPY: https://github.com/ethereum/go-ethereum/blob/v1.10.20/core/vm/instructions.go#L367
- EXTCODECOPY: https://github.com/ethereum/go-ethereum/blob/v1.10.20/core/vm/instructions.go#L386
- CALLDATALOAD: https://github.com/ethereum/go-ethereum/blob/v1.10.20/core/vm/instructions.go#L286
- CALLDATACOPY: https://github.com/ethereum/go-ethereum/blob/v1.10.20/core/vm/instructions.go#L312
- RETURNDATACOPY: https://github.com/ethereum/go-ethereum/blob/v1.10.20/core/vm/instructions.go#L338

Erigon:
- CODECOPY: https://github.com/ledgerwatch/erigon/blob/v2022.07.02/core/vm/instructions.go#L395
- EXTCODECOPY: https://github.com/ledgerwatch/erigon/blob/v2022.07.02/core/vm/instructions.go#L410
- CALLDATALOAD: https://github.com/ledgerwatch/erigon/blob/v2022.07.02/core/vm/instructions.go#L311
- CALLDATACOPY: https://github.com/ledgerwatch/erigon/blob/v2022.07.02/core/vm/instructions.go#L337
- RETURNDATACOPY: https://github.com/ledgerwatch/erigon/blob/v2022.07.02/core/vm/instructions.go#L366

Nethermind
- CODECOPY: https://github.com/NethermindEth/nethermind/blob/1.13.4/src/Nethermind/Nethermind.Evm/VirtualMachine.cs#L1467
- EXTCODECOPY: https://github.com/NethermindEth/nethermind/blob/1.13.4/src/Nethermind/Nethermind.Evm/VirtualMachine.cs#L1533
- CALLDATALOAD: https://github.com/NethermindEth/nethermind/blob/1.13.4/src/Nethermind/Nethermind.Evm/VirtualMachine.cs#L1399
- CALLDATACOPY: https://github.com/NethermindEth/nethermind/blob/1.13.4/src/Nethermind/Nethermind.Evm/VirtualMachine.cs#L1430
- RETURNDATACOPY: https://github.com/NethermindEth/nethermind/blob/1.13.4/src/Nethermind/Nethermind.Evm/VirtualMachine.cs#L1580

Besu:
- CODECOPY: https://github.com/hyperledger/besu/blob/22.4.4/evm/src/main/java/org/hyperledger/besu/evm/operation/CodeCopyOperation.java#L48
- EXTCODECOPY: https://github.com/hyperledger/besu/blob/22.4.4/evm/src/main/java/org/hyperledger/besu/evm/operation/ExtCodeCopyOperation.java#L70
- CALLDATALOAD: https://github.com/hyperledger/besu/blob/22.4.4/evm/src/main/java/org/hyperledger/besu/evm/operation/CallDataLoadOperation.java#L46-L50
- CALLDATACOPY: https://github.com/hyperledger/besu/blob/22.4.4/evm/src/main/java/org/hyperledger/besu/evm/operation/CallDataCopyOperation.java#L49
- RETURNDATACOPY: https://github.com/hyperledger/besu/blob/22.4.4/evm/src/main/java/org/hyperledger/besu/evm/operation/ReturnDataCopyOperation.java#L52

Py-EVM:
- CODECOPY: https://github.com/ethereum/py-evm/blob/v0.5.0-alpha.3/eth/vm/logic/context.py#L125
- EXTCODECOPY: https://github.com/ethereum/py-evm/blob/v0.5.0-alpha.3/eth/vm/logic/context.py#L159
- CALLDATALOAD: https://github.com/ethereum/py-evm/blob/v0.5.0-alpha.3/eth/vm/logic/context.py#L63
- CALLDATACOPY: https://github.com/ethereum/py-evm/blob/v0.5.0-alpha.3/eth/vm/logic/context.py#L91
- RETURNDATACOPY: https://github.com/ethereum/py-evm/blob/v0.5.0-alpha.3/eth/vm/logic/context.py#L207

EthereumJS:
- CODECOPY: https://github.com/ethereumjs/ethereumjs-monorepo/blob/c5260ba9add32f57921380abb32c2c1f9dc21de6/packages/evm/src/opcodes/functions.ts#L474
- EXTCODECOPY: https://github.com/ethereumjs/ethereumjs-monorepo/blob/c5260ba9add32f57921380abb32c2c1f9dc21de6/packages/evm/src/opcodes/functions.ts#L502
- CALLDATALOAD: https://github.com/ethereumjs/ethereumjs-monorepo/blob/c5260ba9add32f57921380abb32c2c1f9dc21de6/packages/evm/src/opcodes/functions.ts#L432
- CALLDATACOPY: https://github.com/ethereumjs/ethereumjs-monorepo/blob/c5260ba9add32f57921380abb32c2c1f9dc21de6/packages/evm/src/opcodes/functions.ts#L452
- RETURNDATACOPY: https://github.com/ethereumjs/ethereumjs-monorepo/blob/c5260ba9add32f57921380abb32c2c1f9dc21de6/packages/evm/src/opcodes/gas.ts#L142-L144

**Comment by antonper** [comment]
@daejunpark Thank you for clarification and deep analysis!
