### ISSUE TITLE
EIP-2929 clarification

### ISSUE THREAD

**Issue by wolflo** [runtimeverification/evm-semantics#987]
The branch [berlin-hardfork](https://github.com/kframework/evm-semantics/tree/berlin-hardfork) adds [EIP-2929](https://eips.ethereum.org/EIPS/eip-2929) to the semantics.

The implementation appears to drop the per-word copy gas from the pricing function for `EXTCODECOPY`. That is, prior to EIP-2929, `EXTCODECOPY` charged `static_cost +  mem_expansion_cost + 3 * data_size_words`. The `static_cost` has been replaced with some variable `access_cost` by EIP-2929, but the berlin-hardfork semantics now charge only `access_cost + mem_expansion_cost`.

Here is the section from the semantics:
```
    rule [Cextcodecopy.new]: Cextcodecopy(SCHED, _WIDTH, ISWARM)  => Caddraccess(SCHED, ISWARM) requires Ghasaccesslist << SCHED >>
    rule [Cextcodecopy.old]:
         Cextcodecopy(SCHED, WIDTH, _ISWARM)
      => Gextcodecopy < SCHED > +Int (Gcopy < SCHED > *Int (WIDTH up/Int 32))
      requires notBool Ghasaccesslist << SCHED >>
```

It's not clear from the EIP itself what the behavior should be, but in the client implementations the copy gas of `3 * data_size_words` is still charged, suggesting that `Cextcodecopy.new` should be replaced with the following:

```
    rule [Cextcodecopy.new]: 
        Cextcodecopy(SCHED, WIDTH, ISWARM)  
    => Caddraccess(SCHED, ISWARM) +Int (Gcopy < SCHED > *Int (WIDTH up/Int 32))
    requires Ghasaccesslist << SCHED >>
```

## Geth implementation

https://github.com/ethereum/go-ethereum/blob/04dcc9378dc38d54eeb6a688d81e8b5e13446519/core/vm/operations_acl.go#L139

https://github.com/ethereum/go-ethereum/blob/04dcc9378dc38d54eeb6a688d81e8b5e13446519/core/vm/gas_table.go#L92

https://github.com/ethereum/go-ethereum/blob/04dcc9378dc38d54eeb6a688d81e8b5e13446519/core/vm/gas_table.go#L78

## OpenEthereum Implementation

https://github.com/openethereum/openethereum/blob/582bca385fedb1af682e989e5bcc6b3b2cf53028/crates/vm/evm/src/interpreter/gasometer.rs#L238-L242

https://github.com/openethereum/openethereum/blob/582bca385fedb1af682e989e5bcc6b3b2cf53028/crates/vm/evm/src/interpreter/gasometer.rs#L368-L370

**Comment by dwightguth** [comment]
Surely it must be intended for the per word cost to still be charged, otherwise users could stall the network by mining a bunch of transactions that copy huge numbers of bytes but cost very little gas.
